### PR TITLE
Quickfix min elevation for new SRTM15+V2.1 earth relief grids

### LINKED ISSUE #399: Some baseline images need to be updated
**Description of the problem**

Some of the pygmt tests are failing, since the GMT team recently upgraded all the earth relief grid files (see https://github.com/GenericMappingTools/gmt/issues/2920). 

We need to update the baseline images of the failing tests.

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Upstream GMT has updated its earth relief grids to SRTM15+V2.1 to fill in NaN values (see https://github.com/GenericMappingTools/gmt/issues/2920). This commit fixes the test failures due to incorrect minimum elevation values, and minor changes to the contour and grid plots.

Supersedes #350

Manually changed the doctests in the `pygmt/clib/session.py` file, and the tests in the `test_datasets.py` and `test_info.py` files. Plus ran the below two commands to generate new baseline images:

```bash
pytest --mpl-generate-path=baseline pygmt/tests/test_grdcontour.py
pytest --mpl-generate-path=baseline pygmt/tests/test_makecpt.py
```

Fixes #399

**Reminders**

- [x] Run `make format` and `make check` to make sure the code follows the style guide.
- [x] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

### CODE REVIEW

**Comment by weiji14** [comment]
Cool, how do you bypass the required check in #397 to merge in the PR? The 'Squash and Merge' button is grayed out for me.

**Comment by seisman** [comment]
It's also gray to me due to the strict branch protection rules. I had to go to "Settings"->"Branches" and change the rules temporarily to allow me merging that PR.

**Comment by weiji14** [comment]
Owh ok, that's annoying. I'll try that...

**Comment by weiji14** [comment]
Cool, I've temporarily disabled the `codecov/patch` requirement until we can create a proper GMT 6.0/6.1 test for #397. Just need to keep note of that.

**Pull request merged**
