### PR TITLE
Expand table-like input options for Figure.contour

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR expands table-like input options for Figure.contour while refactoring to use virtualfile_from_data.

Addresses #949 

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by meghanrjones** [comment]
@weiji14, can you clarify whether each function needs a test for every input option (relates to https://github.com/GenericMappingTools/pygmt/pull/1455#pullrequestreview-759569303)? https://github.com/GenericMappingTools/pygmt/pull/1523 added a test that covers each option (except geopandas). So, to me it seems that using `pytest.mark.parametrize("array_func,kind", [(np.array, "matrix"), (pd.DataFrame, "vector"), (xr.Dataset, "vector")]` for a test in "test_contour.py", "test_surface.py", etc. would be redundant with "pygmt/tests/test_clib.py:test_virtualfile_from_data_required_z_matrix".

**Comment by weiji14** [comment]
> @weiji14, can you clarify whether each function needs a test for every input option (relates to https://github.com/GenericMappingTools/pygmt/pull/1455#pullrequestreview-759569303)? https://github.com/GenericMappingTools/pygmt/pull/1523 added a test that covers each option (except geopandas). So, to me it seems that using `pytest.mark.parametrize("array_func,kind", [(np.array, "matrix"), (pd.DataFrame, "vector"), (xr.Dataset, "vector")]` for a test in "test_contour.py", "test_surface.py", etc. would be redundant with "pygmt/tests/test_clib.py:test_virtualfile_from_data_required_z_matrix".

On second thought, maybe not every function since it does get redundant. But I feel it would be nice to test at least 1 for the clib, 1 data processing function (done for nearneighbor), and 1 for a plotting function. So I'd add a parametrize test to `contour`, but not to others like `plot`, `histogram`, etc.

**Comment by meghanrjones** [comment]
> On second thought, maybe not every function since it does get redundant. But I feel it would be nice to test at least 1 for the clib, 1 data processing function (done for nearneighbor), and 1 for a plotting function. So I'd add a parametrize test to `contour`, but not to others like `plot`, `histogram`, etc.

Thanks for the input, I added one to this PR.

**Review by weiji14 — APPROVED** [review]
Nicely done :)

**Review by seisman — APPROVED** [review]

**Pull request merged**
