### PR TITLE
Update Code of Conduct to v2.1

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Address #1739.

The original markdown text is available at https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by willschlitzer — APPROVED** [review]

**Review by meghanrjones — APPROVED** [review]

**Review by weiji14 — APPROVED** [review]
Thanks @seisman!

Just want to double check though if @leouieda and @PaulWessel are still happy to be listed as contacts? Or we can nominate a new person (e.g. @meghanrjones) as an additional contact.

**Comment by PaulWessel** [comment]
I think for pyGMT it makes more sense to have @meghanrjones listed than me.

**Comment by meghanrjones** [comment]
I can be listed. My SOEST directory page is https://www.soest.hawaii.edu/soestwp/about/directory/meghan-jones/ for people to find out how to get in touch.

**Comment by seisman** [comment]
> I can be listed. My SOEST directory page is [soest.hawaii.edu/soestwp/about/directory/meghan-jones](https://www.soest.hawaii.edu/soestwp/about/directory/meghan-jones/) for people to find out how to get in touch.

I just removed Paul and added Meghan to the list.

**Review by michaelgrund — APPROVED** [review]

**Comment by leouieda** [comment]
I know this is merged to but just wanted to confirm that I'm happy to be listed there as a contact. 👍🏽

**Pull request merged**
