### PR TITLE
Unpin the Sphinx version

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

### CODE REVIEW

**Comment by weiji14** [comment]
So sphinx and sphinx_rtd_theme was pinned at #383, and the main change I notice is a condensed API documentation?

## Old (current):
image

## New (This PR):
image

Doesn't look too bad :smile:

**Comment by seisman** [comment]
It wastes too many spaces on the left side.


image

**Comment by weiji14** [comment]
Yeah it does. I do like how the vertical whitespace is compressed (for the Aliases especially). Maybe we can configure it somehow (looking at https://sphinx-rtd-theme.readthedocs.io/en/stable/index.html), or pin to a different version?

**Comment by seisman** [comment]
Note that we also have a custom [style.css](https://github.com/GenericMappingTools/pygmt/blob/master/doc/_static/style.css) which may or may not be compatible with new sphinx and sphinx_rtd_theme.

**Comment by seisman** [comment]
It seems unpinning the sphinx version doesn't change the appearance of the API documentation.

Can we merge the PR?

**Review by weiji14 — APPROVED** [review]
Interesting, good to unpin it then!

**Pull request merged**
