### PR TITLE
Rename tutorial files to prevent duplicate file names

### LINKED ISSUE #2250: Incorrect build documentation due to identical file names of examples
It seems like it is not allowed by Sphinx-Gallery that two examples have identical filenames, even when they are saved in different folders. Currently, this is the case for:
- Intro to PyGMT - **Create a contour map**: https://www.pygmt.org/dev/get_started/contour_map.html
- Tutorials - **Creating a map with contour lines**: https://www.pygmt.org/dev/tutorials/advanced/contour_map.html

When running `make html` to build the documentation locally, the following warning occurs:
```
WARNING: Duplicate example file name(s) found. Having duplicate file names will break some links.
List of files: ['../examples/get_started/contour_map.py']
```

According to this the documentation for the tutorial is wrongly build:
- correct - v0.7.0: https://www.pygmt.org/latest/tutorials/advanced/contour_map.html
- wrong - dev after adding "Create a contour map": https://www.pygmt.org/dev/tutorials/advanced/contour_map.html

Thus, we have to rename one of these two example files.

### PR DESCRIPTION
**Pull request by willschlitzer**
This adds "tutorial_" to the start of `first_figure.py` and `contour_map.py` to avoid naming conflicts when building documentation.

Fixes #2250 

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by michaelgrund — APPROVED** [review]

**Comment by seisman** [comment]
I don't think I like the new names. The `tutorial_` prefix makes the URL much longer and doesn't provide more information. What about simply renaming `contour_map` to `contours`?

**Comment by willschlitzer** [comment]
> I don't think I like the new names. The `tutorial_` prefix makes the URL much longer and doesn't provide more information. What about simply renaming `contour_map` to `contours`?

I don't feel that strongly about it. I figure that adding `tutorial_` to the front groups the tutorials together, but can also rename it to `contours` if that would make things easier.

@GenericMappingTools/gmt-maintainers Thoughts?

**Comment by michaelgrund** [comment]
> > I don't think I like the new names. The `tutorial_` prefix makes the URL much longer and doesn't provide more information. What about simply renaming `contour_map` to `contours`?
> 
> I don't feel that strongly about it. I figure that adding `tutorial_` to the front groups the tutorials together, but can also rename it to `contours` if that would make things easier.
> 
> @GenericMappingTools/gmt-maintainers Thoughts?

I would prefer @willschlitzer's solution.

**Comment by seisman** [comment]
> > > > I don't think I like the new names. The `tutorial_` prefix makes the URL much longer and doesn't provide more information. What about simply renaming `contour_map` to `contours`?
> > > 
> > > 
> > > I don't feel that strongly about it. I figure that adding `tutorial_` to the front groups the tutorials together, but can also rename it to `contours` if that would make things easier.
> > > @GenericMappingTools/gmt-maintainers Thoughts?
> > 
> > 
> > I would prefer @willschlitzer's solution.
> 
> I like the grouping-effect due to adding `tutorial_` at the beginning of the filenames.

All these files are in the `get_started` directory, so they're already grouped.

**Comment by yvonnefroehlich** [comment]
Ping @weiji14 and @maxrjones for their thoughts and preferences on this, please.

**Comment by weiji14** [comment]
I almost prefer a third option - prefixing with the sequence number of the tutorial (i.e. `01_first_figure`, `02_contour_map`) since they are numbered in https://www.pygmt.org/dev/get_started/index.html. How about we vote for this?

:+1: Prefix with `tutorial_`
:tada: Rename `contour_map` to `contours` and so on
:eyes: Prefix with number (e.g. `01_`, `02_`)

**Comment by seisman** [comment]
> Prefix with number (e.g. `01_`, `02_`)

Prefixing with numbers sounds like a good idea, but the contour tutorial may not be the 2nd tutorial when we add more tutorials in the future, so we may have to rename it in the future.

**Comment by yvonnefroehlich** [comment]
I think I am OK with numbers as prefix.

**Comment by willschlitzer** [comment]
Changed to use numbers.

**Review by weiji14 — APPROVED** [review]

**Review by yvonnefroehlich — APPROVED** [review]

**Review by seisman — APPROVED** [review]

**Pull request merged**
