### PR TITLE
Upgrade gmt from 6.0.0rc1 to 6.0.0rc4

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Testing out the new *patched* GMT 6.0.0rc4 release (see upstream https://github.com/GenericMappingTools/gmt/issues/1471) for PyGMT, a step towards readying it for the GMT6 release coming soon. Full list of changes at https://github.com/GenericMappingTools/gmt/compare/6.0.0rc1...6.0.0rc4 in addition to the patch at https://github.com/conda-forge/gmt-feedstock/pull/85.

Builds upon #311. Might also be a good time to add GMT back to our conda installation (i.e. revert some aspects of https://github.com/GenericMappingTools/pygmt/pull/261).

Noticed some tests were breaking on my local instance when developing on `GMT 6.0.0rc4`, specifically `test_session_management.py` ~~and `test_sphinx_gallery.py`. Has something to do with modern/classic mode incompatibility, possibly because of https://github.com/GenericMappingTools/gmt/issues/1142~~. Tracking and resolving it here in this pull request.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

### CODE REVIEW

**Comment by weiji14** [comment]
It appears that there's a [flaky](https://docs.pytest.org/en/latest/flaky.html#system-state) issue with our tests relying on a global GMT modern session, because we don't do proper setup/teardown of the GMT modern session for each test in PyGMT. With GMT==6.0.0rc4, one of the tests finally broke (see https://travis-ci.org/GenericMappingTools/pygmt/jobs/587246410#L1820-L1823):

https://github.com/GenericMappingTools/pygmt/blob/34f5291a7d756ab3edd97be53e6633f3ee9596f1/pygmt/tests/test_session_management.py#L10-L15

results in:

```python-traceback
E           pygmt.exceptions.GMTCLibError: Module 'end' failed with status code 78:
E           psconvert [ERROR]: Syntax error: Modern GMT mode requires the -F option
E           end [ERROR]: Failed to call psconvert
E           end [ERROR]: process_figures returned error 71
```

Specifically, calling `end()` tries to finalize the plots from the previous test (test_psconvert.py). Actually, I think it tries to finalize all of the preceding plots... Running the tests in parallel using several subprocesses with [`pytest-xdist`](https://github.com/pytest-dev/pytest-xdist) results in a dramatic amount of test failures :fearful:

I can do a quickfix to make the test pass :heavy_check_mark:, but we'll need to sort out this test flakiness at some point.

**Comment by seisman** [comment]
@weiji14 The psconvert errors may be a bug of GMT 6.0.0rc4. See https://github.com/GenericMappingTools/gmt/issues/1636 for discussions.

**Comment by weiji14** [comment]
Good spotting. That '-' thing was definitely easy to miss. I'll wait to see how it gets resolved upstream.

Still feel that each of our unit test files should run in their own separate GMT session (so that it can be paralleled when we have lots of tests to run in the future) but that can be raised in a separate issue.

**Comment by weiji14** [comment]
https://github.com/GenericMappingTools/gmt/pull/1638 is merged in, now awaiting https://github.com/conda-forge/gmt-feedstock/pull/85

**Comment by seisman** [comment]
@weiji14 FYI, https://github.com/conda-forge/gmt-feedstock/pull/85 has been merged.

**Comment by weiji14** [comment]
Ready to review @seisman. I've reinstated some of the conda-forge installation instructions from https://github.com/GenericMappingTools/pygmt/pull/261/files#diff-b50754a7065a1dece18f634c6b5b2633 (with some minor edits).

Also on my university Windows machine trying to get things to work, but will wait for this 6.0.0rc4 branch to be merged first 😄

**Comment by leouieda** [comment]
> Still feel that each of our unit test files should run in their own separate GMT session (so that it can be paralleled when we have lots of tests to run in the future) but that can be raised in a separate issue.

This was something I debated a lot in the beginning. The truth is that our users will be relying on there being a single modern mode session that can survive making several plots. So testing in isolation doesn't really tell us if the package works as expected.

**Pull request merged**
