### PR TITLE
Add the badge for black code style in README.rst

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Give credit to [`black`](https://github.com/psf/black) by adding the badge.

[Code style: black](https://github.com/psf/black)

### CODE REVIEW

**Comment by seisman** [comment]
There is a badge for isort:

[Imports: isort](https://pycqa.github.io/isort/)

Do we want to add this one?

**Comment by weiji14** [comment]
There's even a badge for `docformatter`, where do we stop? :laughing:

[](https://github.com/PyCQA/docformatter)

**Comment by seisman** [comment]
Then we have three options:

1. Don't add any of them, i.e., close the PR
2. Only add the badge for black, i.e., merge this PR as it is
3. Add all the three badges.

I'd vote for option 1.

**Comment by weiji14** [comment]
Yeah, I would vote for 1 too, there's a lot of badges already on the main README.md.

**Comment by michaelgrund** [comment]
I also vote for 1.

**Comment by seisman** [comment]
Can someone approve this PR?

**Review by michaelgrund — APPROVED** [review]

**Comment by michaelgrund** [comment]
You mean close the PR?

**Pull request closed without merging**
