### PR TITLE
Figure.legend: Add alias "clearance" for "C"

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

This PR adds the alias `clearance` for **C** of `Figure.legend`.

Please note that there is also the **+c** modifier of the `box` parameter (**F**), which allows specifying all four gaps separately. However, for me, this only has an effect in case a width (**+w**) is given via the `position` parameter (**D**).

Upstream GMT documentation: 
- [legend **-C**](https://docs.generic-mapping-tools.org/dev/legend.html#c)
- [legend **-F**](https://docs.generic-mapping-tools.org/dev/legend.html#f)

GMT Julia documentation:
- https://www.generic-mapping-tools.org/GMTjl_doc/documentation/modules/legend/index.html#legend

**Preview**: https://pygmt-dev--2985.org.readthedocs.build/en/2985/api/generated/pygmt.Figure.legend.html

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash command is:

- `/format`: automatically format and lint the code

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
> > Please note that there is also the **+c** modifier of the `box` parameter (**F**), which allows specifying all four gaps separately. However, for me, this only has an effect in case a width (**+w**) is given via the `position` parameter (**D**).
> 
> Interesting. Need some tests to understand the differences.

Yep, I also was not aware of this, until yesterday. Here is the code I tried:
```python
import pygmt

size = 5
proj = "X7c"
reg = [-size, size, -size, size]

fig = pygmt.Figure()

# -----------------------------------------------------------------------------
# No space modification
fig.basemap(region=reg, projection=proj, frame=["af", "+tno space modification"])

fig.plot(x=0, y=1, style="c0.3c", label="Circle")
fig.plot(x=0, y=-1, style="s0.3c", label="Square")
fig.legend()

fig.shift_origin(xshift="w+1c")

# -----------------------------------------------------------------------------
# Pass +c to the box parameter
fig.basemap(region=reg, projection=proj, frame=["af", "+t+c to box"])

fig.plot(x=0, y=1, style="c0.3c", label="Circle")
fig.plot(x=0, y=-1, style="s0.3c", label="Square")
# left_gap/right_gap/bottom_gap/top_gap
fig.legend(box="+p1p,black+c0.1c/0.4c/1c/0.5c")

fig.shift_origin(xshift="w+1c")

# -----------------------------------------------------------------------------
# Pass +c to the box parameter
# Pass +w to the position parameter to give a width
fig.basemap(region=reg, projection=proj, frame=["af", "+t+c to box and \\053w to position"])

fig.plot(x=0, y=1, style="c0.3c", label="Circle")
fig.plot(x=0, y=-1, style="s0.3c", label="Square")
fig.legend(position="JTR+jTR+w2c", box="+p1p,black+c0.1c/0.4c/1c/0.5c")

fig.shift_origin(xshift="w+1c")

# -----------------------------------------------------------------------------
# Use C flag of Figure.legend
fig.basemap(region=reg, projection=proj, frame=["af", "+tC flag of legend"])

fig.plot(x=0, y=1, style="c0.3c", label="Circle")
fig.plot(x=0, y=-1, style="s0.3c", label="Square")
# x_gap/y_gap
fig.legend(C="0.5c/1c")

fig.show()
```

_Output figure_:
legend_gap_box_entries

**Comment by seisman** [comment]
I find the behaviors are difficult to understand. Maybe file an upstream issue?

**Comment by yvonnefroehlich** [comment]
> I find the behaviors are difficult to understand. Maybe file an upstream issue?

Opened an issue at https://github.com/GenericMappingTools/gmt/issues/8303.

**Comment by yvonnefroehlich** [comment]
Following PR https://github.com/GenericMappingTools/gmt/pull/8305, **-C** is not removed from the code but is not recommended, and users should use **-F+c**. With this solution, adding an alias for **C** is probably not needed anymore, and we can close this PR?

**Pull request closed without merging**
