### PR TITLE
pygmt.Figure.colorbar: Add aliases for L and Z

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**
This PR aims to add aliases for `pygmt.Figure.colorbar`:
- [x] **L** -> `equalsize` (no hypen)
- [x] **Z** -> `zfile`

At the moment the aliases are orientated on the Julia documentation at https://www.generic-mapping-tools.org/GMTjl_doc/documentation/modules/colorbar/. 

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
I am wondering whether it would be nice to update one or both of these two examples
- [3-D Scatter plots](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html)
- [Color points by categories](https://www.pygmt.org/dev/gallery/3d_plots/scatter3d.html)

to use ``equalsize`` (**L**)  with ``pygmt.Figure.colorbar`` (in a separate PR).
What do @GenericMappingTools/pygmt-maintainers think about this change?

**Comment by yvonnefroehlich** [comment]
> > I am wondering whether it would be nice to update one or both of these two examples
> > 
> > * [3-D Scatter plots](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html)
> > * [Color points by categories](https://www.pygmt.org/dev/gallery/3d_plots/scatter3d.html)
> > 
> > to use `equalsize` (**L**) with `pygmt.Figure.colorbar` (in a separate PR). What do @GenericMappingTools/pygmt-maintainers think about this change?
> 
> I think adding `L` makes no changes to these examples.

Hm. I was refering to this change of the colorbar via **L** or `equalsize`:

|  | [Color points by categories](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html) | [3-D Scatter plots](https://www.pygmt.org/dev/gallery/3d_plots/scatter3d.html) |
|---|---|---|
|current version `colorbar()`| pygmt_pingues_colorbar | pygmt_iris_colorbar |
|using `colorbar(equalsize=0.7)` | pygmt_pingues_colorbar_L | pygmt_iris_colorbar_L |

But it's only a detail, and I am also fine with leaving these examples as is 🙂. Another possibility to show this option could the example [Colorbar](https://www.pygmt.org/dev/gallery/embellishments/colorbar.html)?

**Comment by michaelgrund** [comment]
> Hm. I was refering to this change of the colorbar via **L** or `equalsize`:
> 	[Color points by categories](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html) 	[3-D Scatter plots](https://www.pygmt.org/dev/gallery/3d_plots/scatter3d.html)
> current version `colorbar()` 	pygmt_pingues_colorbar 	pygmt_iris_colorbar
> using `colorbar(equalsize=0.7)` 	pygmt_pingues_colorbar_L 	pygmt_iris_colorbar_L
> 
> But it's only a detail, and I am also fine with leaving these examples as is slightly_smiling_face. Another possibility to show this option could be the example [Colorbar](https://www.pygmt.org/dev/gallery/embellishments/colorbar.html)?

From the context side it does not make any difference to use `equalsize` since the data is categorical and thus independent of the colorbar style with or without gaps between the categories. Maybe it's better to show that option in another example or in an potential short tutorial on how to use different styles of colorbars with PyGMT?

**Comment by yvonnefroehlich** [comment]
> > Hm. I was refering to this change of the colorbar via **L** or `equalsize`:
> > But it's only a detail, and I am also fine with leaving these examples as is slightly_smiling_face. Another possibility to show this option could be the example [Colorbar](https://www.pygmt.org/dev/gallery/embellishments/colorbar.html)?
> 
> From the context side it does not make any difference to use `equalsize` since the data is categorical and thus independent of the colorbar style with or without gaps between the categories. Maybe it's better to show that option in another example or in an potential short tutorial on how to use different styles of colorbars with PyGMT?

Yes, sure, this is only an option how to display a colormap for categorical data 🙂.
In general, I am open for a short tutorial on how to use different styles of colorbar with PyGMT. But there is already the Gallery example [Colorbar](https://www.pygmt.org/dev/gallery/embellishments/colorbar.html) which covers several options on displaying colormaps.

**Comment by seisman** [comment]
> In general, I am open for a short tutorial on how to use different styles of colorbar with PyGMT. But there is already the Gallery example [Colorbar](https://www.pygmt.org/dev/gallery/embellishments/colorbar.html) which covers several options on displaying colormaps.

I think it's OK if you want to improve the [Colorbar](https://www.pygmt.org/dev/gallery/embellishments/colorbar.html) example, but it can be done in a separate PR.

**Review by seisman — APPROVED** [review]

**Review by weiji14 — APPROVED** [review]

**Pull request merged**
