### PR TITLE
Set timeout limit for CI tests

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

Occasionally, the CI tests get caught and timeout after 6 hours. Given that the tests should complete within 30 minutes, this PR proposes to set [timeout-minutes](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) to end after 60 minutes rather than the default of 360.

To-do:
- [x] Set limit for dev tests

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
Perhaps also set the timeout limit for the `ci_docs.yml` workflow?

**Comment by willschlitzer** [comment]
I think this is a good idea, and agree that 30 minutes should be enough.

**Comment by weiji14** [comment]
> Perhaps also set the timeout limit for the `ci_docs.yml` workflow?

Probably don't need to, since the Docs workflow doesn't use `dvc` (which is what the CI gets stuck on usually).

**Comment by seisman** [comment]
> > Perhaps also set the timeout limit for the `ci_docs.yml` workflow?
> 
> Probably don't need to, since the Docs workflow doesn't use `dvc` (which is what the CI gets stuck on usually).

But it does no harm to timeout the workflow after 30 minutes, considering that the workflow should finish in 20 minutes.

**Comment by meghanrjones** [comment]
OK, I added a limit to the docs workflow.

**Review by weiji14 — APPROVED** [review]

**Review by seisman — APPROVED** [review]

**Pull request merged**
