### PR TITLE
Pin version of CI scripts to 1.0.0

### PR DESCRIPTION
**Pull request by leouieda**
Don't clone from master to avoid breaking the builds when the scripts
update.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

### CODE REVIEW

**Comment by leouieda** [comment]
@seisman could you configure appveyor to only build branches with a `.appveyor.yml`? I don't have access to the admin panel since you set it up.

**Comment by seisman** [comment]
@leouieda I've removed pygmt from appveyor, since currently we don't have an .appveyor.yml file.

**Comment by leouieda** [comment]
Thanks, @seisman. I'm trying out Azure Pipelines for Windows. Seems to be better and faster.

**Comment by seisman** [comment]
@leouieda I'm also trying to build gmt for windows using Azure Pipelines. It takes only 10 minutes for one build, much faster than appveyor.

**Comment by leouieda** [comment]
:+1: yep. It's kind of complicated and I hate their sintax but it's a lot faster.

**Pull request merged**
