### PR TITLE
Improve tutorial frames.py

### LINKED ISSUE #2021: Unclear introduction sentence of Tutorial 'Frames, ticks, titles, and labels'
The introduction sentence of the tutorial [Frames, ticks, titles, and labels](https://www.pygmt.org/dev/tutorials/basics/frames.html#frames-ticks-titles-and-labels) makes no sense and is incomplete:

> Setting the style of the map frames, ticks, etc, is handled by the frame parameter that all plotting methods of pygmt.Figure.

Probably / At least the verb is missing, maybe something like "have" or "contain"? I did not control, if all methods of the class [`pygmt.Figure`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.html#pygmt.Figure) have the `frame` parameter. Maybe this formulation can be indirectly misleading regarding the method [`pygmt.Figure.colorbar`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.colorbar.html#pygmt.Figure.colorbar), since there the `frame`parameter manipulates not the frame of the map, but the frame of the colorbar.

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

This PR aims to improve the tutorial [Frames, ticks, titles, and labels](https://www.pygmt.org/dev/tutorials/basics/frames.html#sphx-glr-tutorials-basics-frames-py).

Fixes #2021 

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
In the section [Ticks and grid lines](https://www.pygmt.org/dev/tutorials/basics/frames.html#ticks-and-grid-lines):

`frame=True` seems not exactly to equal `frame='a'`, but seems to be similar to `frame='af'`. For `frame=True` there are additional minor tick marks (without tick labels).

------------------
In the section [Axis labels](https://www.pygmt.org/dev/tutorials/basics/frames.html#axis-labels):
> Axis labels can be set by passing x+llabel (or starting with y if labeling the y-axis) to the frame parameter of pygmt.Figure.basemap. By default, all 4 map boundaries (or plot axes) are plotted with both tick marks and axis labels. The axes are named as W (west/left), S (south/bottom), N (north/top), and E (east/right) sides of a figure. If an upper-case axis name is passed, the axis is plotted with tick marks and axis labels. A lower case axis name plots only the axis and tick marks.
>
> The example below uses a Cartesian projection, as GMT does not allow axis labels to be set for geographic maps.

Some remarks / questions:
- Potentially mixing of _tick_ labels (`'a'`, e.g. 1, 2, 3, ...) and _axis_ labels (`'+llabel'`, e.g. x-axis). 
- Is it really the case that _"...[b]y default all 4 map boundaries (or plot axes) are plotted with both tick marks and [tick] labels"_? I think by default, only the west/right and the south/bottom axes have tick marks (`frame='f'`) or both tick marks and tick labels (`frame='a'`, `frame=True`).
- Maybe we should mention the option to use `'r'`, `'b'`, `'t'`, `'l'` to plot only the axis (neither tick marks nor tick labels)?
- Maybe we should explain how the steps of ticks marks (`'f'`), tick labels (`'a'`), and grid lines (`'g'`) can be adjusted for personal needs (e.g. `frame='a1f1g1'`). Or do the last two points exceed a basis tutorial?

**Comment by seisman** [comment]
> In the section [Ticks and grid lines](https://www.pygmt.org/dev/tutorials/basics/frames.html#ticks-and-grid-lines):
> 
> `frame=True` seems not exactly to equal `frame='a'`, but seems to be similar to `frame='af'`. For `frame=True` there are additional minor tick marks (without tick labels).
> 

Yes.

> In the section [Axis labels](https://www.pygmt.org/dev/tutorials/basics/frames.html#axis-labels):
> 
> > Axis labels can be set by passing x+llabel (or starting with y if labeling the y-axis) to the frame parameter of pygmt.Figure.basemap. By default, all 4 map boundaries (or plot axes) are plotted with both tick marks and axis labels. The axes are named as W (west/left), S (south/bottom), N (north/top), and E (east/right) sides of a figure. If an upper-case axis name is passed, the axis is plotted with tick marks and axis labels. A lower case axis name plots only the axis and tick marks.
> > The example below uses a Cartesian projection, as GMT does not allow axis labels to be set for geographic maps.
> 
> Some remarks / questions:
> 
> * Potentially mixing of _tick_ labels (`'a'`, e.g. 1, 2, 3, ...) and _axis_ labels (`'+llabel'`, e.g. x-axis). See [367f934](https://github.com/GenericMappingTools/pygmt/commit/367f934ab66e90fc839504e72675ea5a66a49f27)

In GMT, _tick_ labels like 1, 2, 3 are called annotations, and axis labels (e.g., x-axis) are simply called labels.

> * Is it really the case that _"...[b]y default all 4 map boundaries (or plot axes) are plotted with both tick marks and [tick] labels"_? I think by default, only the west/right and the south/bottom axes have tick marks (`frame='f'`) or both tick marks and tick labels (`frame='a'`, `frame=True`).

Yes, the default has been changed from `WSEN` to `WSen` in recent GMT versions. 

> * Maybe we should mention the option to use `'r'`, `'b'`, `'t'`, `'l'` to plot only the axis (neither tick marks nor tick labels)?

Sounds good to me.

> * Maybe we should explain how the steps of ticks marks (`'f'`), tick labels (`'a'`), and grid lines (`'g'`) can be adjusted for personal needs (e.g. `frame='a1f1g1'`). Or do the last two points exceed a basis tutorial?

Sounds good to me.

**Comment by yvonnefroehlich** [comment]
> > In the section [Ticks and grid lines](https://www.pygmt.org/dev/tutorials/basics/frames.html#ticks-and-grid-lines):
> > `frame=True` seems not exactly to equal `frame='a'`, but seems to be similar to `frame='af'`. For `frame=True` there are additional minor tick marks (without tick labels).
> 
> Yes.
> 
See https://github.com/GenericMappingTools/pygmt/pull/2023/commits/6c67aadfe14df9b73e1fc8a8dbb1b23615de3ab4.

---------------

> > In the section [Axis labels](https://www.pygmt.org/dev/tutorials/basics/frames.html#axis-labels):
> > 
> > * Potentially mixing of _tick_ labels (`'a'`, e.g. 1, 2, 3, ...) and _axis_ labels (`'+llabel'`, e.g. x-axis). See [367f934](https://github.com/GenericMappingTools/pygmt/commit/367f934ab66e90fc839504e72675ea5a66a49f27)
> 
> In GMT, _tick_ labels like 1, 2, 3 are called annotations, and axis labels (e.g., x-axis) are simply called labels.
> 
Oh yes, sure! See https://github.com/GenericMappingTools/pygmt/pull/2023/commits/146b185f8acdcfb3cb81d0a1529d4ea7debbd0ba.
> > * Is it really the case that _"...[b]y default all 4 map boundaries (or plot axes) are plotted with both tick marks and [tick] labels"_? I think by default, only the west/right and the south/bottom axes have tick marks (`frame='f'`) or both tick marks and tick labels (`frame='a'`, `frame=True`).
> 
> Yes, the default has been changed from `WSEN` to `WSen` in recent GMT versions.
> 
Thanks for the info! See https://github.com/GenericMappingTools/pygmt/pull/2023/commits/895f39cc47acea06235b328657f7329067474c11.
I think we also have to update the gallery example [Double Y axes graph](https://www.pygmt.org/dev/gallery/basemaps/double_y_axes.html#sphx-glr-gallery-basemaps-double-y-axes-py). There is some overlap between this gallery example and the frame-tutorial.

> > * Maybe we should mention the option to use `'r'`, `'b'`, `'t'`, `'l'` to plot only the axis (neither tick marks nor tick labels)?
> 
> Sounds good to me.
> 
See https://github.com/GenericMappingTools/pygmt/pull/2023/commits/2a69852a15e4241a308a7acac733686ec1ed5bfb and https://github.com/GenericMappingTools/pygmt/pull/2023/commits/4a6621fe7c537c9e194d7dcd9b12b0caed147aa2.

> > * Maybe we should explain how the steps of ticks marks (`'f'`), tick labels (`'a'`), and grid lines (`'g'`) can be adjusted for personal needs (e.g. `frame='a1f1g1'`). Or do the last two points exceed a basis tutorial?
> 
> Sounds good to me.
>
Try do this the next days.

**Review by seisman — APPROVED** [review]

**Comment by seisman** [comment]
@yvonnefroehlich Looks good to me. 

Remove "WIP" from the PR title and add the "final review call" label?

**Pull request merged**
