### PR TITLE
Update fatiando continuous integration scripts from 1.1.1 to 1.2.0

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Fixes randomly failing Mac builds. See release notes at https://github.com/fatiando/continuous-integration/releases/tag/1.2.0.

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

### CODE REVIEW

**Comment by weiji14** [comment]
@leouieda, `sudo chown` doesn't work... Crossref https://github.com/fatiando/continuous-integration/pull/19.

**Comment by weiji14** [comment]
Ah yes that makes sense, I saw that code block but thought it runs inside the CI script. Things should work now :crossed_fingers:

**Comment by weiji14** [comment]
I'd love to but can't... As mentioned in #317, there's something about GMT organization's permissions that's stopping me from pushing or creating branches directly here.

**Comment by leouieda** [comment]
@weiji14 could you try again? That's not right and we should get this sorted.

**Comment by weiji14** [comment]
Nope, still not working :cry: I reckon it's my two factor authentication that's the problem, am I the only one in GMT using it? Look at https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/viewing-whether-users-in-your-organization-have-2fa-enabled

**Comment by leouieda** [comment]
It shouldn't be because I've had that on for years now.

**Comment by leouieda** [comment]
I just tripple checked and you're part of the `python` team which has admin rights to this repository. So you should be able to push (not to the master branch, though). What sort of error are you getting?

**Comment by weiji14** [comment]
Ok, not sure what happened, but I can push to and create branches on [GenericMappingTools](https://github.com/GenericMappingTools) repos properly now, including [branches on the FOSS4G 2019 Oceania](https://github.com/GenericMappingTools/foss4g2019oceania/branches) repo! And that's via SSH as well. Did you change something?

**Pull request merged**
