### PR TITLE
Consistently pass keyword arguments when using call_module()

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

When calling the `call_module()` method, we use two different styles:

1. Pass positional arguments
```
lib.call_module("triangulate", build_arg_string(kwargs, infile=infile))
```
2. Pass keyword arguments
```
lib.call_module(module="triangulate", args=build_arg_string(kwargs, infile=infile))
```

The two styles work the same way, but it's better to use a single style in the project.

I prefer the first style (passing positional arguments) because it's shorter.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by weiji14** [comment]
I kinda prefer the longer kwargs version though, easier to see what the parameters are, especially for newcomers. Maybe get a vote on this?

**Comment by seisman** [comment]
> I kinda prefer the longer kwargs version though, easier to see what the parameters are, especially for newcomers. Maybe get a vote on this?

Here are the main reasons that I prefer the short version:

- `call_module`'s arguments are positional arguments, so `module=` and `args=` are not required
- The function only has two arguments, and it's easy to guess the meaning of the two arguments
- it's shorter. In some functions, it can be written in a single line rather than 4 lines.

**Comment by willschlitzer** [comment]
I'm also a fan of the keyword arguments. I understand that it's pretty clear which argument is being used as there are only two, but I think it's always best to remove any chance for ambiguity.

**Comment by seisman** [comment]
OK, I've updated all `call_module()` calls using the keyword arguments. The exceptions are a few doctests in `pygmt/clib.session.py` and tests in `pygmt/tests/test_session_management.py` and `pygmt/tests/test_clib.py`.

**Review by weiji14 — APPROVED** [review]

**Pull request merged**
