### PR TITLE
Fix several failures due to updates of earth relief data

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Update some numbers due to the recent changes in GMT earth relief data.

Partially address #451.

Note: For unknown reasons, the caches of the Azure Pipelines expire and there is always a cache miss. 
Each CI job will download the data files from the GMT data server. 

It seems the long-time internet connection issue in Azure Pipelines is gone, and all files are downloaded without timeouts.

**Reminders**

- [x] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

### CODE REVIEW

**Comment by weiji14** [comment]
> Note: For unknown reasons, the caches of the Azure Pipelines expire and there is always a cache miss.
> Each CI job will download the data files from the GMT data server.
> 
> It seems the long-time internet connection issue in Azure Pipelines is gone, and all files are downloaded without timeouts.

Does that mean we don't need the cross-platform workaround as in #438 anymore?

**Comment by seisman** [comment]
> > Note: For unknown reasons, the caches of the Azure Pipelines expire and there is always a cache miss.
> > Each CI job will download the data files from the GMT data server.
> > It seems the long-time internet connection issue in Azure Pipelines is gone, and all files are downloaded without timeouts.
> 
> Does that mean we don't need the cross-platform workaround as in #438 anymore?

Not sure. It yes, the GitHub Actions CI (#475) would be greatly simplified. 🤞

**Comment by seisman** [comment]
Now there are only 13 failures (image differences). 

Two of the Windows CI jobs still fail to download the earth_relief_10m grid, leading to one more failure.

**Comment by weiji14** [comment]
> Two of the Windows CI jobs still fail to download the earth_relief_10m grid, leading to one more failure.

Should we merge in #495 first then, just to update the cache key and see if will work?

**Comment by weiji14** [comment]
OR, we can merge #495 into this PR, and then merge this PR into master.

**Comment by seisman** [comment]
I don't think PR #495 really updates the caches. Look at the [latest CI reports of that PR](https://dev.azure.com/GenericMappingTools/PyGMT/_build/results?buildId=8730&view=logs&jobId=83531d48-723a-5b90-a05f-13015d7b6edc&j=83531d48-723a-5b90-a05f-13015d7b6edc&t=4cf99463-c004-53b8-38d1-ee605688348c), it still tries to download all the files.

Possibly because the caching post-job won't run if the any CI steps fail.

**Comment by seisman** [comment]
Should we move all the closed issues linked to [the 0.2.x milestone](https://github.com/GenericMappingTools/pygmt/milestone/2?closed=1) to [0.1.x milestone](https://github.com/GenericMappingTools/pygmt/milestone/1)?

**Comment by weiji14** [comment]
Done, and I'll move some of the open ones to 0.1.x too.

**Pull request merged**
