### PR TITLE
clib.conversion._to_numpy: Add tests for pandas.Series with pyarrow date32/date64 types

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Add tests for panda.Series with pyarrow date32/date64 dtypes.

In PR #2845, we added the support of `date32[day][pyarrow]` and `date64[ms][pyarrow]` and mapped them to `np.datetime64`. This PR improves it and maps them to `"datetime64[D]"` and `datetim64[ms]` respectively.

After approval, I plan to cherry-pick changes in e13b5d32b98408827f797003ebe3f591f89213a0 into a separate PR so that we can have a changelog entry.

### CODE REVIEW

**Review by michaelgrund — APPROVED** [review]

**Comment by seisman** [comment]
Ping @weiji14 for final reviews on the `date32`/`date64` behavior changes.

**Comment by weiji14** [comment]
Maybe update the test here too to check explicitly for "datetime64[D]"/"datetim64[ms]" instead of just `np.datetime64`?

https://github.com/GenericMappingTools/pygmt/blob/9a12ae907d55b95b08d0665d9f548ee9f9133c3b/pygmt/tests/test_clib_vectors_to_arrays.py#L89-L100

**Comment by seisman** [comment]
Actually I feel the test `test_vectors_to_arrays_pyarrow_datetime` can be removed, since it's already covered by the newly added tests in this PR.

**Review by weiji14 — APPROVED** [review]
> Actually I feel the test `test_vectors_to_arrays_pyarrow_datetime` can be removed, since it's already covered by the newly added tests in this PR.

On second thought, maybe keep the test. we need to test that `vectors_to_arrays` can handle mixed dtypes (and that test checks both date32/date64) from a pandas.DataFrame or nested list, whereas `_to_numpy` is for single dtypes on a pandas.Series or single list.

**Pull request merged**
