### PR TITLE
Fix typos in syntax of the projection documentation

### LINKED ISSUE #2059: Inconsistent syntax for projections in documentation
For some of the [Py]GMT projections the syntax is inconsistent between the [PyGMT overview table](https://www.pygmt.org/dev/projections/index.html#projection-table) and the specific documentation page, e.g.:
- [Mercator projection](https://www.pygmt.org/dev/projections/cyl/cyl_mercator.html)
- [Transverse Mercator projection](https://www.pygmt.org/dev/projections/cyl/cyl_transverse_mercator.html)
- [Cylindrical stereographic](https://www.pygmt.org/dev/projections/cyl/cyl_stereographic.html)
- [Equidistant cylindrical](https://www.pygmt.org/dev/projections/cyl/cyl_equidistant.html)

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

This PR aims to fix some typos in the syntax of the projections, including both the overview table and the separate documentation pages.

Start in #2253
Fixes #2059

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
Additionally to the typo fixes, I expanded the docs for the [Cylinderical equistant projection](https://www.pygmt.org/dev/projections/cyl/cyl_equidistant.html) based on the [upstrem GMT documentation](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#cylindrical-equidistant-projection-jq-jq) (I saw the typo "map map" in the subsection Parameters).

The same is needed for the [Polyconic projection](https://www.pygmt.org/dev/projections/conic/polyconic.html). Here the [upstream GMT documentation](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#american-polyconic-projection-jpoly-jpoly) seems to contain a copy-past-error (please see the subsection Parameters) from the Lambert conic conformal projection above. I have to understand how the Polyconic projection works before I can update the docs (I never used this projection) 🙂. Currently I don't know what `lat0` does or should do. I wrote a code example (PyGMT dev, GMT 6.4) in which `lat0` is varied, but all figures look the same (please see below). @GenericMappingTools/pygmt-maintainers maybe one of you has already used this projection and can help out, please.

**Code example** 
```python
# source: https://www.pygmt.org/dev/projections/conic/polyconic.html
# last access: 2022/12/24
# modification: variation of lat0
import pygmt

lat0 = [-40, -30, -20, -10, 0, 10, 20, 30, 40, 50, 60, 70, 80]

for lat0_i in lat0:
    
    fig = pygmt.Figure()
    fig.coast(
        shorelines="1/0.5p",
        region=[-180, -20, 0, 90],
        projection="Poly/-100/" + str(lat0_i) + "/12c",
        land="gray",
        borders="1/thick,black",
        frame="afg10",
    )
    fig.text(
        position="TL",
        text="lat0 = " + str(lat0_i) + " deg",
    )
    fig.show()
```

**Output figure** (for all lat0 values)
Poly10

**Comment by yvonnefroehlich** [comment]
@GenericMappingTools/pygmt-maintainers can you please review this PR (I apologize for getting headache from this 😕).

**Review by seisman — APPROVED** [review]

**Comment by seisman** [comment]
> Additionally to the typo fixes, I expanded the docs for the [Cylinderical equistant projection](https://www.pygmt.org/dev/projections/cyl/cyl_equidistant.html) based on the [upstrem GMT documentation](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#cylindrical-equidistant-projection-jq-jq) (I saw the typo "map map" in the subsection Parameters).
> 
> The same is needed for the [Polyconic projection](https://www.pygmt.org/dev/projections/conic/polyconic.html). Here the [upstream GMT documentation](https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html#american-polyconic-projection-jpoly-jpoly) seems to contain a copy-past-error (please see the subsection Parameters) from the Lambert conic conformal projection above. I have to understand how the Polyconic projection works before I can update the docs (I never used this projection) 🙂. Currently I don't know what `lat0` does or should do. I wrote a code example (PyGMT dev, GMT 6.4) in which `lat0` is varied, but all figures look the same (please see below). @GenericMappingTools/pygmt-maintainers maybe one of you has already used this projection and can help out, please.
> 
> **Code example**
> 
> ```python
> # source: https://www.pygmt.org/dev/projections/conic/polyconic.html
> # last access: 2022/12/24
> # modification: variation of lat0
> import pygmt
> 
> lat0 = [-40, -30, -20, -10, 0, 10, 20, 30, 40, 50, 60, 70, 80]
> 
> for lat0_i in lat0:
>     
>     fig = pygmt.Figure()
>     fig.coast(
>         shorelines="1/0.5p",
>         region=[-180, -20, 0, 90],
>         projection="Poly/-100/" + str(lat0_i) + "/12c",
>         land="gray",
>         borders="1/thick,black",
>         frame="afg10",
>     )
>     fig.text(
>         position="TL",
>         text="lat0 = " + str(lat0_i) + " deg",
>     )
>     fig.show()
> ```
> 
> **Output figure** (for all lat0 values) Poly10

Ping @PaulWessel for comments on this.

**Comment by PaulWessel** [comment]
Let's see if @remkos has thoughts since I am pretty sure he added this projection.

**Review by michaelgrund — APPROVED** [review]

**Pull request merged**
