### PR TITLE
Bump the GMT version to 6.5.0

### PR DESCRIPTION
**Pull request by michaelgrund**
**Description of proposed changes**

Address #2961 

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash command is:

- `/format`: automatically format and lint the code

### CODE REVIEW

**Comment by seisman** [comment]
No, we're still going to support GMT 6.3 and 6.4. So, the minimum required version is still 6.3.0.

**Comment by michaelgrund** [comment]
> No, we're still going to support GMT 6.3 and 6.4. So, the minimum required version is still 6.3.0.

You mean in `ci_tests_legacy.yaml`?

**Comment by seisman** [comment]
`required_version` should be `6.3.0` so that PyGMT works with GMT 6.3, 6.4 and 6.5.

**Comment by seisman** [comment]
On other words, none of the changes in this PR makes sense, so the PR should be closed.

**Comment by michaelgrund** [comment]
> In other words, none of the changes in this PR make sense, so the PR should be closed.

Then we should remove the corresponding TODOs in #2961

**Comment by seisman** [comment]
> > In other words, none of the changes in this PR make sense, so the PR should be closed.
> 
> Then we should remove the corresponding TODOs in #2961

Yes, done.

**Pull request closed without merging**
