### PR TITLE
Unset GMT_DATA_SERVER and use the default value

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

As mentioned in https://github.com/GenericMappingTools/pygmt/issues/1556#issuecomment-932614258, the GMT server issue has been fixed. Now it's OK to use the default GMT server URL.

Partially reverts #1553.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by weiji14** [comment]
Do we need to uncache the `@N30W120.earth_relief_15s_p.nc` tile? I see that https://github.com/GenericMappingTools/gmt/issues/5829 has been closed in https://github.com/GenericMappingTools/gmt/pull/5834. Otherwise we might forget to uncache that tile when PyGMT bumps to GMT>=6.3.
`

**Comment by seisman** [comment]
Uncaching the `@N30W120.earth_relief_15s_p.nc` tile means that building the documentation will take more time for downloading the tile and may fail on Windows and macOS due to GitHub Action internet connection issues.

I'm OK with delaying this PR after we bump to GMT 6.3.0.

**Comment by weiji14** [comment]
> Uncaching the `@N30W120.earth_relief_15s_p.nc` tile means that building the documentation will take more time for downloading the tile and may fail on Windows and macOS due to GitHub Action internet connection issues.
> 
> I'm OK with delaying this PR after we bump to GMT 6.3.0.

Well, I quite like using https (kinda surprised the default is http to be honest). Let's keep the `GMT_DATA_SERVER` setting on for a little longer :slightly_smiling_face:

**Comment by weiji14** [comment]
Do you think we could use this branch (or open another PR) to see how many tests break in PyGMT with the new SRTM v2.3 earth_relief grids? Specifically, by setting `GMT_DATA_SERVER=https://test.generic-mapping-tools.org` (xref https://github.com/GenericMappingTools/gmtserver-admin/pull/118) on the macOS workflow for `ci_tests.yaml`.

**Comment by meghanrjones** [comment]
> Do you think we could use this branch (or open another PR) to see how many tests break in PyGMT with the new SRTM v2.3 earth_relief grids? Specifically, by setting `GMT_DATA_SERVER=https://test.generic-mapping-tools.org` (xref [GenericMappingTools/gmtserver-admin#118](https://github.com/GenericMappingTools/gmtserver-admin/pull/118)) on the macOS workflow for `ci_tests_dev.yaml`.

The ssl certificate isn't set up, so I don't think https would work yet. I've asked about getting it updated.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
