### PR TITLE
ruff: Fix Python 3.10 violations

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Fixes the following ruff violations with Python 3.10+
- [x] B905 [*] zip() without an explicit strict= parameter - https://docs.astral.sh/ruff/rules/zip-without-explicit-strict
- [x] UP035 [*] Import from collections.abc instead: Callable - https://docs.astral.sh/ruff/rules/deprecated-import
- [x] UP038 Use `X | Y` in `isinstance` call instead of `(X, Y)` - https://docs.astral.sh/ruff/rules/non-pep604-isinstance (should we ignore this, because the docs says `X | Y` might be slower than `(X, Y)`?)

Addresses https://github.com/GenericMappingTools/pygmt/pull/3039#issuecomment-1927252931

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash command is:

- `/format`: automatically format and lint the code

### CODE REVIEW

**Comment by weiji14** [comment]
> [ ] UP038 Use `X | Y` in `isinstance` call instead of `(X, Y)` - https://docs.astral.sh/ruff/rules/non-pep604-isinstance (should we ignore this, because the docs says `X | Y` might be slower than `(X, Y)`?)

Do we want to ignore UP038, or change to `isinstance(..., X | Y)`? I can run some benchmarks to see if it's slower.

**Review by seisman — APPROVED** [review]
Looks good.

**Comment by weiji14** [comment]
Wanted to double-check the flame graphs, so I manually triggered the benchmarks workflow on the main branch to get the baseline (following steps at https://github.com/GenericMappingTools/pygmt/issues/2910#issuecomment-1928722002). Will merge this after I've had a look at the timing comparison.

**Comment by weiji14** [comment]
Hmm, still not seeing the flame graph, but the performance benchmark didn't report the run as noticeably slower https://github.com/GenericMappingTools/pygmt/pull/3040/checks?check_run_id=21254596529, so should be ok.

**Pull request merged**
