### PR TITLE
WIP: CI: Use iterative/setup-dvc to install dvc

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

dvc has a complicated dependency and sometimes dvc fails to work due to incompatible changes of other packges (e.g., https://github.com/GenericMappingTools/pygmt/issues/1693, https://github.com/GenericMappingTools/pygmt/issues/1543, https://github.com/GenericMappingTools/pygmt/pull/2338, and recent https://github.com/GenericMappingTools/pygmt/pull/2464#issuecomment-1487613519).

In this PR, I tried to use the [`iterative/setup-dvc`](https://github.com/iterative/setup-dvc) action to install dvc instead of manually installing `dvc` using mamba. It turns out the `iterative/setup-dvc` action provides a more stable dvc installation. However, `iteractive/setup-dvc` is extremely slow on Windows (takes about 2.5 minutes).

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by weiji14** [comment]
> Regarding the title, are more changes expected on this PR?

> > However, `iteractive/setup-dvc` is extremely slow on Windows (takes about 2.5 minutes).

Probably need to consider if we want to accept a slower Windows build.

**Comment by maxrjones** [comment]
> > Regarding the title, are more changes expected on this PR?
> 
> > > However, `iteractive/setup-dvc` is extremely slow on Windows (takes about 2.5 minutes).
> 
> Probably need to consider if we want to accept a slower Windows build.

My preference is to prioritize functionality (in this case executing the tests completely) over speed. If pinning `funcy` provides a faster solution that seems like a good alternative.

**Comment by weiji14** [comment]
> > > Regarding the title, are more changes expected on this PR?
> > 
> > 
> > > > However, `iteractive/setup-dvc` is extremely slow on Windows (takes about 2.5 minutes).
> > 
> > 
> > Probably need to consider if we want to accept a slower Windows build.
> 
> My preference is to prioritize functionality (in this case executing the tests completely) over speed. If pinning `funcy` provides a faster solution that seems like a good alternative.

The `funcy` error was actually fixed in `dvc` already at https://github.com/iterative/dvc/pull/9279, but unsure when they'll cut a new release :slightly_smiling_face:

**Comment by maxrjones** [comment]
> > > > Regarding the title, are more changes expected on this PR?
> > > 
> > > 
> > > > > However, `iteractive/setup-dvc` is extremely slow on Windows (takes about 2.5 minutes).
> > > 
> > > 
> > > Probably need to consider if we want to accept a slower Windows build.
> > 
> > 
> > My preference is to prioritize functionality (in this case executing the tests completely) over speed. If pinning `funcy` provides a faster solution that seems like a good alternative.
> 
> The `funcy` error was actually fixed in `dvc` already at [iterative/dvc#9279](https://github.com/iterative/dvc/pull/9279), but unsure when they'll cut a new release 🙂

Nice! Seems like their release frequency is pretty high, so we may be able to wait. Though it would be best to have the tests passing before our release.

**Comment by seisman** [comment]
I think we should pin funcy temporarily to make the tests pass So we can have the0.9.0 release done.

**Comment by weiji14** [comment]
Did you want to keep this `iterative/setup-dvc` workflow or close it?

**Comment by seisman** [comment]
Closing this PR.

**Pull request closed without merging**
