### PR TITLE
Update URLs in intersphinx mapping

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

- Update to new numpy site
- Use https

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by weiji14 — APPROVED** [review]
Looks like #839 works :smile:

**Comment by seisman** [comment]
Oh yes. I was wondering why the actions didn't start.

**Comment by seisman** [comment]
Perhaps we should move "style check" to a separate workflow, so that "Style Check" always runs?

**Comment by weiji14** [comment]
> Perhaps we should move "style check" to a separate workflow, so that "Style Check" always runs?

Sure, I can do that in a second.

**Comment by seisman** [comment]
> > Perhaps we should move "style check" to a separate workflow, so that "Style Check" always runs?
> 
> Sure, I can do that in a second.

Great. Please do it.

**Pull request merged**
