### PR TITLE
Move non-plotting modules to separate files in src directory

### LINKED ISSUE #807: Should data processing functions have their own modules?
In #685, @weiji14 asked the question of if data processing modules like `makecpt` and `grd2cpt` should be split into their own Python scripts, much like the plotting modules will be. My opinion is they should be split up. The other files aren't nearly as big as `base_plotting.py`, but I think it's best to standardize all functions in this way, and it makes it easier to find the function you're looking for (I wasn't sure if `grd2cpt` should be under `mathops.py` or `grdops.py`?).

I'm happy to do it. I'm assuming the process would be similar to the changes in `base_plotting.py`, and just involve copying the functions to their own scripts in `pygmt.src`, but how do we "tell" PyGMT where to look for it beyond the init file, as there isn't a base_plotting-equivalent script to import into?

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Part 1 of fixing #807

**Reminders**

- [x] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
All tests still pass and the API documentation looks good.

**Comment by willschlitzer** [comment]
Do we want to make separate folders and __init__.py files in the src folder to import the functions for mathops/gridops/etc.? There aren't a ton of non-plotting functions that are wrapped, but I figure this would keep the overall number of imports into the main pyGMT script low, especially as our numbers of wrapped modules increase.

**Comment by seisman** [comment]
> Do we want to make separate folders and **init**.py files in the src folder to import the functions for mathops/gridops/etc.? 

I don't think so. Like what you said in #807, if we make separate folders, we still have to decide "if grd2cpt.py should be under mathops/ or grdops/?"

**Comment by willschlitzer** [comment]
Good point!

**Comment by seisman** [comment]
I almost finished the moving of non-plotting modules, except a few functions that need more discussion:

- `grdinfo`: will move after #799 to avoid conflicts
- `config`: wrapper of GMT's `set` command. `pygmt/config.py`? `pygmt/src/config.py`? `pygmt/src/set.py`?
- `GMTDataArrayAccessor`: `pygmt/datatypes`?
- `x2sys_init` and `x2sys_cross`: do we want to put these functions into two files or one file `pygmt/src/x2sys.py`?

**Comment by seisman** [comment]
Ping @GenericMappingTools/python and @GenericMappingTools/python-maintainers for comments on https://github.com/GenericMappingTools/pygmt/pull/832#issuecomment-773777917

**Comment by weiji14** [comment]
> I almost finished the moving of non-plotting modules, except a few functions that need more discussion:

Maybe split it into 2 PRs. Name this Part 1 and merge it first, and then we do the ones below in a Part 2 PR.

> - `grdinfo`: will move after #799 to avoid conflicts

Agree. Or should we just finish this PR (#832) and move `grdinfo` directly under src/ in #799?

> - `config`: wrapper of GMT's `set` command. `pygmt/config.py`? `pygmt/src/config.py`? `pygmt/src/set.py`?
> - `GMTDataArrayAccessor`: `pygmt/datatypes.py`?

I would leave these in modules.py for now since they're both classes. We can review them for v0.4.0.

> - `x2sys_init` and `x2sys_cross`: do we want to put these functions into two files or one file `pygmt/src/x2sys.py`?

This is a hard one. There are a few other `x2sys` modules which are still unwrapped. I would keep them in one file for now (keeps the diff small), but probably need to split them up in the future.

**Comment by seisman** [comment]
> Maybe split it into 2 PRs. Name this Part 1 and merge it first, and then we do the ones below in a Part 2 PR.

Sounds good. Now this PR is ready for review.

**Review by weiji14 — APPROVED** [review]
Cool, thanks @seisman, not easy moving so many files! I see a lot of places where we could use f-strings and update the documentation following the convention agreed in #775 but those can be addressed in the future to keep the diff small here.

**Pull request merged**
