### PR TITLE
Rename tutorial.py to samples.py

### PR DESCRIPTION
**Pull request by michaelgrund**
**Description of proposed changes**

As discussed in #1101 here's a PR to rename ``tutorial.py`` (in which functions are defined to load sample data from the GMT tutorials) to ``samples.py``.

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by seisman — CHANGES_REQUESTED** [review]
Please also update the docstrings. Currently, it still says

> Functions to load sample data from the GMT tutorials.

Also, rename `pygmt/tests/test_datasets_tutorial.py` to `pygmt/tests/test_datasets_samples.py`.

**Comment by michaelgrund** [comment]
> 
> 
> Please also update the docstrings. Currently, it still says
> 
> > Functions to load sample data from the GMT tutorials.
> 
> Also, rename `pygmt/tests/test_datasets_tutorial.py` to `pygmt/tests/test_datasets_samples.py`.

Done in a750769 @seisman!

**Review by seisman — APPROVED** [review]
Looks good. 

Changes in this PR will conflict with your PR #794. Do you want to merge this PR first, and solve the conflicts in PR #794, or the other way around?

**Comment by michaelgrund** [comment]
> 
> 
> Looks good.
> 
> Changes in this PR will conflict with your PR #794. Do you want to merge this PR first, and solve the conflicts in PR #794, or the other way around?

Yes, noticed that, will solve the conflict in #794 @seisman .

**Review by meghanrjones — APPROVED** [review]

**Review by weiji14 — APPROVED** [review]

**Comment by weiji14** [comment]
I think we can just merge this as is without waiting, so that the load fracture sample data PR at #1101 can move forward. @michaelgrund has been very patient with wrapping the `rose` function and there's been a lot of sidetracks 🙂 

Can you merge this PR in by yourself @michaelgrund once all the tests pass? Just need to click on the green 'Squash and Merge' button, and make sure to tidy up the commit message a bit (describe what was done in this PR and remove unnecessary lines like '* updated __init__.py').

**Pull request merged**
