### PR TITLE
Unpin sphinx_rtd_theme from 0.5.1

### LINKED ISSUE #1176: Wrong style of toctree caption due to breaking changes in docutils 0.17
**Description of the problem**

Go to https://www.pygmt.org/dev/, you will see:

image

The toctree captions don't show correctly, dut to breaking changes in docutils 0.17.

See related bug reports and possible fixes:

- https://github.com/readthedocs/sphinx_rtd_theme/issues/1112
- https://github.com/readthedocs/sphinx_rtd_theme/issues/1111
- https://github.com/sphinx-doc/sphinx/issues/9001
- https://github.com/sphinx-doc/sphinx/pull/9059

I think we need to pin docutils to 0.16 as a workaround, and wait for upstream fixes. Agree?

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR unpins sphinx_rtd_theme so that 0.5.2 will be used when available on conda-forge, which has docutils pinned at 0.16. 

Relates to #1176

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by meghanrjones** [comment]
Should we pin to 0.5.2 here or just take out the version number so that it uses latest?

**Comment by meghanrjones** [comment]
> Should we pin to 0.5.2 here or just take out the version number so that it uses latest?

0.5.2 was not available on conda-forge yet so the checks failed. I think unpinning sphinx_rtd_theme is the best solution here so that 0.5.2 will be used when available.

**Comment by seisman** [comment]
sphinx_rtd_theme v0.5.2 was released two hours ago. I think we should wait for a few more days to use v0.5.2.

BTW, do you test that sphinx_rtd_theme v0.5.2 can fix #1176? I don't see any commits/changes related to docutils v0.17.

**Comment by meghanrjones** [comment]
> sphinx_rtd_theme v0.5.2 was released two hours ago. I think we should wait for a few more days for the conda-forge update.

Do you think we should keep updating the pinned version or simply unpin to use the latest version on conda-forge? 

> BTW, do you test that sphinx_rtd_theme v0.5.2 can fix #1176? I don't see any commits/changes related to docutils v0.17.

Yes, sphinx_rtd_theme v0.5.2 can fix #1176. See the [release changes](https://github.com/readthedocs/sphinx_rtd_theme/compare/0.5.1...0.5.2) for the relevant updates (sphinx_rtd_theme is pinning docutils). I verified locally by installing all the dependencies using conda-forge except sphinx_rtd_theme, which I added to the environment from PyPi (which has v0.5.2). But, this PR would have no affect until v0.5.2 is on conda-forge.

**Comment by weiji14** [comment]
Just wait a bit longer, things will be ok once https://github.com/conda-forge/sphinx_rtd_theme-feedstock/pull/21 is merged.

**Comment by seisman** [comment]
> > sphinx_rtd_theme v0.5.2 was released two hours ago. I think we should wait for a few more days for the conda-forge update.
> 
> Do you think we should keep updating the pinned version or simply unpin to use the latest version on conda-forge?

I think it's not necessary to pin the theme version.

**Review by weiji14 — APPROVED** [review]
> > > sphinx_rtd_theme v0.5.2 was released two hours ago. I think we should wait for a few more days for the conda-forge update.
> > 
> > 
> > Do you think we should keep updating the pinned version or simply unpin to use the latest version on conda-forge?
> 
> I think it's not necessary to pin the theme version.

Agree. Let's just merge this in then, and things should automatically get fixed once https://github.com/conda-forge/sphinx_rtd_theme-feedstock/pull/21 is merged and sphinx_rtd_theme 0.5.2 is available on conda-forge.

**Pull request merged**
