### PR TITLE
Move codecov.yml into .github directory and increase coverage target to 90 percent

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

One less configuration file to see in the top level directory.
See https://docs.codecov.io/docs/codecov-yaml#can-i-name-the-file-codecovyml

Helps with #904 

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by seisman — APPROVED** [review]
Great!

**Comment by weiji14** [comment]
Just wondering, do we want to increase the target coverage from 80% to 90% (or higher)? We've been tracking at above 95% for the past six months it seems.

7iwb5xau

https://github.com/GenericMappingTools/pygmt/blob/f0a6a64ea49d4ff99de0aeb7f2c10e86f765a4b0/.github/codecov.yml#L5-L9

**Comment by seisman** [comment]
> do we want to increase the target coverage from 80% to 90% (or higher)? We've been tracking at above 95% for the past six months it seems.

I'm fine with 90% or 95% coverage.

**Comment by weiji14** [comment]
Ok, increased to 90%. Merging.

**Comment by seisman** [comment]
image

I think we misunderstand what 90% means. 

We set the target of **patches** to 90%. I think it means at least 90% of the changed lines should be covered.

It's different than the **project** coverage. If I understand it correctly, the **project** coverage only pass if the current coverage is no smaller than the previous coverage.

**Comment by weiji14** [comment]
> image
> 
> I think we misunderstand what 90% means.
> 
> We set the target of **patches** to 90%. I think it means at least 90% of the changed lines should be covered.
> 
> It's different than the **project** coverage. If I understand it correctly, the **project** coverage only pass if the current coverage is no smaller than the previous coverage.

Ah, so we need to set the **project** coverage as well then perhaps, in addition to the **patch** coverage?

**Comment by seisman** [comment]
Maybe, but I didn't read the codecov documentation carefully.

**Pull request merged**
