### PR TITLE
Correct and consistent usage of 'function, 'method', and 'class'

### LINKED ISSUE #2029: Inconsistent usage of 'function' and 'method'
It seems that the terms 'function' and 'method' are used exchangeable in the tutorial and gallery examples.

From my understanding, in Python a method belongs to a class and is associated with / called on an object. This is consistent to the API Documentation of the [`pygmt.Figure`](https://www.pygmt.org/dev/api/generated/pygmt.Figure.html) class.

However,
- there are examples which use 'function' for the methods of the `pygmt.Figure` class, e.g.:
  - [Making subplots](https://www.pygmt.org/dev/tutorials/advanced/subplots.html#define-subplot-layout): The `pygmt.Figure.subplot` function
- there are examples which use 'method' for the tabular and raster data processing functions, e.g.:
  - [Generate points along great circles](https://www.pygmt.org/dev/gallery/lines/great_circles.html#generate-points-along-great-circles): The `pygmt.project` method
  - [Create ‘wet-dry’ mask grid](https://www.pygmt.org/dev/gallery/images/grdlandmask.html#create-wet-dry-mask-grid): The `pygmt.grdlandmask` method
  - [Blockmean](https://www.pygmt.org/dev/gallery/histograms/blockm.html#blockmean): The `pygmt.blockmean` method

I think, we should be precise and consistent with the terminology (at least in the way that something is always either a function or a method) to avoid confusions.

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

Fixes #2029 

--------

**Overview of affected files**

- [ ] Cross-check in the end regarding completeness

_Examples which use 'function' for the methods of the `pygmt.Figure` class_
- [x] [Making subplots](https://www.pygmt.org/dev/tutorials/advanced/subplots.html#define-subplot-layout)
- [x] [Setting the region](https://www.pygmt.org/dev/tutorials/basics/regions.html#sphx-glr-tutorials-basics-regions-py)
- [x] [Adding an inset to the figure](https://www.pygmt.org/dev/tutorials/advanced/insets.html#sphx-glr-tutorials-advanced-insets-py)
- [x] [Performing grid histogram equalization](https://www.pygmt.org/dev/tutorials/advanced/grid_equalization.html#sphx-glr-tutorials-advanced-grid-equalization-py)
- [x] [Inset](https://www.pygmt.org/dev/gallery/embellishments/inset.html#sphx-glr-gallery-embellishments-inset-py)
- [x] [Inset map showing a rectangular region](https://www.pygmt.org/dev/gallery/embellishments/inset_rectangle_region.html#sphx-glr-gallery-embellishments-inset-rectangle-region-py)

_Examples which use 'method' for the tabular and raster data processing functions_
- [x] [Generate points along great circles](https://www.pygmt.org/dev/gallery/lines/great_circles.html#generate-points-along-great-circles)
- [x] [Create ‘wet-dry’ mask grid](https://www.pygmt.org/dev/gallery/images/grdlandmask.html#create-wet-dry-mask-grid)
- [x] [Blockmean](https://www.pygmt.org/dev/gallery/histograms/blockm.html#blockmean)
- [x] [Calculating grid gradient and radiance](https://www.pygmt.org/dev/gallery/images/grdgradient.html#sphx-glr-gallery-images-grdgradient-py)
- [x] [Clipping grid values](https://www.pygmt.org/dev/gallery/images/grdclip.html#sphx-glr-gallery-images-grdclip-py)
- [x] [Plotting Earth relief](https://www.pygmt.org/dev/tutorials/advanced/earth_relief.html#sphx-glr-tutorials-advanced-earth-relief-py)
- [x] [Color points by categories](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html#sphx-glr-gallery-symbols-points-categorical-py) [see below]
- [x] [Multiple colormaps](https://www.pygmt.org/dev/gallery/embellishments/colorbars_multiple.html#sphx-glr-gallery-embellishments-colorbars-multiple-py) [see below]

_API documentation (list is incomplete and was not continued)_
- [x] figure.py / psconvert
- [x] [table](https://www.pygmt.org/dev/api/index.html#configuring-the-display-settings) [see below]

----------

I am unsure about the usage of the term 'module'. I remember issue https://github.com/GenericMappingTools/pygmt/issues/1828 and PR https://github.com/GenericMappingTools/pygmt/pull/1858 which are about whether `pygmt.Figure.coast` is a 'module' or 'method'.

- `pygmt.set_display`
    - in [API doc table](https://www.pygmt.org/dev/api/index.html?highlight=module#configuring-the-display-settings): 'module'
- `pygmt.grd2cpt`
    - in [API doc table](https://www.pygmt.org/dev/api/index.html?highlight=module#configuring-the-display-settings): 'module'
    - in [API doc text](https://www.pygmt.org/dev/api/generated/pygmt.grd2cpt.html?highlight=method): 'method'
- `pygmt.makecpt`
    - in [API doc table](https://www.pygmt.org/dev/api/index.html?highlight=module#configuring-the-display-settings): 'module'
    - in [API doc text](https://www.pygmt.org/dev/api/generated/pygmt.makecpt.html?highlight=method#pygmt.makecpt): 'method'
    - in [Color points by categories](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html#sphx-glr-gallery-symbols-points-categorical-py) and [Multiple colormaps](https://www.pygmt.org/dev/gallery/embellishments/colorbars_multiple.html#sphx-glr-gallery-embellishments-colorbars-multiple-py): 'method'

I am definitely not a Python expert! Probably 'module' is inferred from GMT, but the three listed above do not appear to be 'modules' in the _Pythonic-sense_ `from xy_module import xy_function` (see also second paragraph of issue https://github.com/GenericMappingTools/pygmt/issues/1828#issue-1172574530). Maybe it was overlook to also change the [API doc table](https://www.pygmt.org/dev/api/index.html?highlight=module#configuring-the-display-settings) in PR https://github.com/GenericMappingTools/pygmt/pull/1858. But why they are 'methods', as changed in PR https://github.com/GenericMappingTools/pygmt/pull/1858, despite they do not belong to a class or called on an object? I would be very happy about an explanation for understanding (: In case they are neither 'modules' nor 'methods', it appears that they are 'functions'. Ping @seisman, @maxrjones, @michaelgrund, @willschlitzer (, and @weiji14) for thoughts and help on this, please.

-----------------

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by maxrjones** [comment]
Thanks for working on this!

While there could be exceptions, I think the use of module anywhere in PyGMT's docs likely comes from GMT-centric language and not from any Python-related definition. So unless specifically referring to GMT, these could be updated to "function" or "method".

You are correct that `pygmt.set_display`, `pygmt.grd2cpt`, and `pygmt.makecpt` are functions.

**Comment by yvonnefroehlich** [comment]
> Thanks for working on this!

I am happy to contribute, and at least partly I feel I learn more than I bring to the project :wink:

> While there could be exceptions, I think the use of module anywhere in PyGMT's docs likely comes from GMT-centric language and not from any Python-related definition. So unless specifically referring to GMT, these could be updated to "function" or "method".

Thanks @maxrjones for your explanation! :slightly_smiling_face:

> You are correct that `pygmt.set_display`, `pygmt.grd2cpt`, and `pygmt.makecpt` are functions.

I have made the changes in  https://github.com/GenericMappingTools/pygmt/pull/2043/commits/b313a67ccea9e2fbaf3c33a705a3b44c4c0fa46a as well as https://github.com/GenericMappingTools/pygmt/pull/2043/commits/0b13099f44a4d800c7e0c88483633266ca4f6d96 and https://github.com/GenericMappingTools/pygmt/pull/2043/commits/80339ebd1be9869fd186e8266210c7c31ea82644. Try to continue with the remaining examples in the next days.

**Comment by yvonnefroehlich** [comment]
I have now updated all examples listed above.

**Comment by seisman** [comment]
@yvonnefroehlich Please resolve the conflicts first.

**Review by seisman — APPROVED** [review]
Looks great!

**Review by michaelgrund — APPROVED** [review]

**Comment by seisman** [comment]
@yvonnefroehlich I saw you added "WIP" to the PR title. Are there any more changes you want to make to this PR?

**Comment by yvonnefroehlich** [comment]
> @yvonnefroehlich I saw you added "WIP" to the PR title. Are there any more changes you want to make to this PR?

Yes. I am sorry. I overlooked to check the cases which have not explicitly `function/method/class` written
after the function/method/class name.

**Comment by seisman** [comment]
> > @yvonnefroehlich I saw you added "WIP" to the PR title. Are there any more changes you want to make to this PR?
> 
> Yes. I am sorry. I overlooked to check the cases which have not explicitly `function/method/class` written after the function/method/class name.

No worries. We'll give it another round of review when you finish it/

**Comment by yvonnefroehlich** [comment]
In [first_figure.py](https://www.pygmt.org/dev/get-started/first_figure.html#sphx-glr-get-started-first-figure-py):

> To add to a plot object (fig in this example), the PyGMT module is used as a method on the class. This example will use the [pygmt.Figure.coast](https://www.pygmt.org/dev/api/generated/pygmt.Figure.coast.html#pygmt.Figure.coast) method, which can be used to create a map without any other methods, modules or external data. The [pygmt.Figure.coast](https://www.pygmt.org/dev/api/generated/pygmt.Figure.coast.html#pygmt.Figure.coast) method plots the coastlines, borders, and bodies of water using a database that is included in GMT.

I am unsure about the formulations in this part. Should we keep `modules` in `... other methods, modules or external data ...` or change it to `functions`? PyGMT itself does not have modules in a Pythonic sense. But maybe "modules" is referring to `numpy`,  `pandas`, etc.?

**Comment by seisman** [comment]
> In [first_figure.py](https://www.pygmt.org/dev/get-started/first_figure.html#sphx-glr-get-started-first-figure-py):
> 
> > To add to a plot object (fig in this example), the PyGMT module is used as a method on the class. This example will use the [pygmt.Figure.coast](https://www.pygmt.org/dev/api/generated/pygmt.Figure.coast.html#pygmt.Figure.coast) method, which can be used to create a map without any other methods, modules or external data. The [pygmt.Figure.coast](https://www.pygmt.org/dev/api/generated/pygmt.Figure.coast.html#pygmt.Figure.coast) method plots the coastlines, borders, and bodies of water using a database that is included in GMT.
> 
> I am unsure about the formulations in this part. Should we keep `modules` in `... other methods, modules or external data ...` or change it to `functions`? PyGMT itself does not have modules in a Pythonic sense. But maybe "modules" is referring to `numpy`, `pandas`, etc.?

I think it originally means "GMT's modules". 

Because this is the first PyGMT tutorial and the potential PyGMT users may have never used GMT before, I think it makes very little sense to mention any GMT concepts (e.g., modules) here. So, it's OK to say "without any other methods or external data."

**Comment by seisman** [comment]
> To add to a plot object (`fig` in this example), the PyGMT module is used as a method on the class.

I also feel that this sentence is a little confusing, because "the PyGMT module" actually means "GMT modules".

**Comment by yvonnefroehlich** [comment]
> > In [first_figure.py](https://www.pygmt.org/dev/get-started/first_figure.html#sphx-glr-get-started-first-figure-py):
> > > To add to a plot object (fig in this example), the PyGMT module is used as a method on the class. This example will use the [pygmt.Figure.coast](https://www.pygmt.org/dev/api/generated/pygmt.Figure.coast.html#pygmt.Figure.coast) method, which can be used to create a map without any other methods, modules or external data. The [pygmt.Figure.coast](https://www.pygmt.org/dev/api/generated/pygmt.Figure.coast.html#pygmt.Figure.coast) method plots the coastlines, borders, and bodies of water using a database that is included in GMT.
> > 
> > 
> > I am unsure about the formulations in this part. Should we keep `modules` in `... other methods, modules or external data ...` or change it to `functions`? PyGMT itself does not have modules in a Pythonic sense. But maybe "modules" is referring to `numpy`, `pandas`, etc.?
> 
> I think it originally means "GMT's modules".
> 
> Because this is the first PyGMT tutorial and the potential PyGMT users may have never used GMT before, I think it makes very little sense to mention any GMT concepts (e.g., modules) here. So, it's OK to say "without any other methods or external data."

Done in https://github.com/GenericMappingTools/pygmt/pull/2043/commits/3e91e11e60426f728865e219cf41bbfbc5fb1bc7.


> > To add to a plot object (`fig` in this example), the PyGMT module is used as a method on the class.
> 
> I also feel that this sentence is a little confusing, because "the PyGMT module" actually means "GMT modules".

I agree. I already have tried to reformulate this sentence, but I was unsure. Thanks @seisman for this explanation! I have made a suggestion in https://github.com/GenericMappingTools/pygmt/pull/2043/commits/3db83c838a242625662a3f98f92e6396608ec07c. Of course, I am totally open for changes and improvements on this.

**Comment by seisman** [comment]
@yvonnefroehlich Reviewing big PRs is more challenging and takes more time than small PRs. I think this PR already has a lot of good changes and should be merged into the main branch after reviewing. 

If you think there are still many files that need to be updated, you can open separate PRs later, like what we did in PRs https://github.com/GenericMappingTools/pygmt/pull/1857, https://github.com/GenericMappingTools/pygmt/pull/1862, https://github.com/GenericMappingTools/pygmt/pull/1872.

**Comment by seisman** [comment]
@yvonnefroehlich Reviewing big PRs is more challenging and takes more time than small PRs. I think this PR already has a lot of good changes and should be merged into the main branch after reviewing. 

If you think there are still many files that need to be updated, you can open separate PRs later, like what we did in PRs https://github.com/GenericMappingTools/pygmt/pull/1857, https://github.com/GenericMappingTools/pygmt/pull/1862, https://github.com/GenericMappingTools/pygmt/pull/1872.

**Comment by yvonnefroehlich** [comment]
> No worries. We'll give it another round of review when you finish it/

Thanks for  your understanding @seisman!

> @yvonnefroehlich Reviewing big PRs is more challenging and takes more time than small PRs. I think this PR already has a lot of good changes and should be merged into the main branch after reviewing.
> 
> If you think there are still many files that need to be updated, you can open separate PRs later, like what we did in PRs #1857, #1862, #1872.

That's fine for me! :wink:

**Review by seisman — APPROVED** [review]

**Review by michaelgrund — APPROVED** [review]

**Pull request merged**
