### PR TITLE
Migrate Figure.legend tests to use dvc

### PR DESCRIPTION
**Pull request by willschlitzer**
Per #1131, this moves the reference figures in `fig.legend` to use `dvc`.

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by willschlitzer** [comment]
@GenericMappingTools/python Any idea why I'm getting a deployment error on this pull request?

**Comment by michaelgrund** [comment]
> 
> 
> @GenericMappingTools/python Any idea why I'm getting a deployment error on this pull request?

No idea, the other PR's work quite well.

**Review by weiji14 — APPROVED** [review]
> > @GenericMappingTools/python Any idea why I'm getting a deployment error on this pull request?
> 
> No idea, the other PR's work quite well.

Could be an intermittent issue, try merging in the master branch to trigger a new deployment to see if it's ok. Anyways, this PR looks good to merge.

**Review by michaelgrund — APPROVED** [review]
Ready to merge!

**Pull request merged**
