### PR TITLE
Improve gallery examples

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

- Use SI units
- Improve some comments
- Improve some external references
- Improve some stylings
- Remove some links to the GMT documentation (We should refer users to the PyGMT API references).

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Notes**

- You can write `/format` in the first line of a comment to lint the code automatically

### CODE REVIEW

**Comment by weiji14** [comment]
Could we speed-up two of the slowest (>10s) tutorial examples you mentioned in #825 in this PR?

> computation time summary:
> - ../examples/tutorials/regions.py:                                            11.34 sec   0.0 MB
> - ../examples/tutorials/3d-perspective-image.py:                      10.06 sec   0.0 MB

**Comment by seisman** [comment]
> Could we speed-up two of the slowest (>10s) tutorial examples you mentioned in #825 in this PR?
> 
> > computation time summary:
> > 
> > * ../examples/tutorials/regions.py:                                            11.34 sec   0.0 MB
> > * ../examples/tutorials/3d-perspective-image.py:                      10.06 sec   0.0 MB

Tried to speed up `regions.py` by removing the `borders` arguments. The running time reduces from 11 s to 8 s. Still slow. The main issue in `regions.py` is that it contains too many similar figures.

**Comment by seisman** [comment]
I prefer to leave them to another PR.

**Comment by seisman** [comment]
Ping @weiji14 for a review.

**Review by weiji14 — APPROVED** [review]

**Pull request merged**
