### PR TITLE
Update pygmt.config baseline images for GMT 6.2.0rc1

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Updates baseline images for the `pygmt.config` tests.

Addresses #1217

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
`test_config_font_annot.png`: the annotations near the needle are wrong, right?

**Comment by weiji14** [comment]
> `test_config_font_annot.png`: the annotations near the needle are wrong, right?

Yeah, why is it -4 instead of 4? Upstream bug?

**Comment by meghanrjones** [comment]
> > `test_config_font_annot.png`: the annotations near the needle are wrong, right?
> 
> Yeah, why is it 4 instead of -4? Upstream bug?
> 
> https://github.com/GenericMappingTools/pygmt/blob/3a4f2f5ad546e2b7196d84099c126e1c5ca113a1/pygmt/tests/test_config.py#L55-L64
> 
> Same case with test_config_font_one.png

This is a consequence of FORMAT_GEO_MAP changing from ddd:mm:ss to ddd:mm:ssF. Feel free to open a GMT issue if you think FORMAT_GEO_MAP should not change these annotations.

**Comment by weiji14** [comment]
> This is a consequence of FORMAT_GEO_MAP changing from ddd:mm:ss to ddd:mm:ssF. Feel free to open a GMT issue if you think FORMAT_GEO_MAP should not change these annotations.

Ok, I see at https://docs.generic-mapping-tools.org/6.2.0rc1/theme-settings.html#default-settings-for-build-in-themes that [`FORMAT_GEO_MAP`](https://docs.generic-mapping-tools.org/6.2.0rc1/gmt.conf.html#term-FORMAT_GEO_MAP) defaults to ddd:mm:ssF for the new 'modern' GMT theme. where `F` is the 'Encode sign using WESN suffix'.

image

@meghanrjones, could you link to the discussion on why `ddd:mm:ssF` is used? Just want to have an informed opinion on this.

**Comment by meghanrjones** [comment]
> @meghanrjones, could you link to the discussion on why `ddd:mm:ssF` is used? Just want to have an informed opinion on this.

If there was a discussion about this, it would have happened in this PR: https://github.com/GenericMappingTools/gmt/pull/3344. I do not remember any discussion after Paul's initial suggestion that maps should have the indicators on them, but I may have missed it.

It might be possible to have an `auto` option for FORMAT_GEO_MAP similar to the new [auto selection](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#automatic-gmt-settings) for some other parameters, which would add WESN suffix for map annotations but not for the declination annotation. But, I haven't looked through how this would work when for example both basemap frame and compass are used so it's just an off-hand idea.

**Comment by weiji14** [comment]
> > @meghanrjones, could you link to the discussion on why `ddd:mm:ssF` is used? Just want to have an informed opinion on this.
> 
> If there was a discussion about this, it would have happened in this PR: [GenericMappingTools/gmt#3344](https://github.com/GenericMappingTools/gmt/pull/3344). I do not remember any discussion after Paul's initial suggestion that maps should have the indicators on them, but I may have missed it.
> 
> It might be possible to have an `auto` option for FORMAT_GEO_MAP similar to the new [auto selection](https://docs.generic-mapping-tools.org/dev/cookbook/features.html#automatic-gmt-settings) for some other parameters, which would add WESN suffix for map annotations but not for the declination annotation. But, I haven't looked through how this would work when for example both basemap frame and compass are used so it's just an off-hand idea.

Thanks Meghan. Combing through the ~250 comments, the only reference I can find on `ddd.:mm:ssF` is Paul's initial comment at https://github.com/GenericMappingTools/gmt/pull/3344#issuecomment-629737443. I think it relates to his point on:

> 4. I think maps should have W-E-S-N indicators on them

which makes sense. Looking more closely at the changed figure, I think it's fine without the minus sign, the plot is actually correct because the declination annotation says 4°30**W** to indicate that it is pointing to the **W**est. Before (in GMT 6.1.1), it would just use -4°30'.

image

In this case, can I get an approval for this PR? Unless there are other concerns.

**Comment by seisman** [comment]
I think it's weird to add **E** or **W** suffix to declination angles. Ping @PaulWessel to confirm whether it's a bug or expected.

**Review by seisman — APPROVED** [review]
After reading the [magnetic declination wikipedia page](https://en.wikipedia.org/wiki/Magnetic_declination), I realize that both `-4°30'` and `4°30'W` are correct expressions for magnetic declination. 

Now this PR is good to merge.

**Review by michaelgrund — APPROVED** [review]
Looks good to me.

**Pull request merged**
