### PR TITLE
Bump sphinx_rtd_theme from 0.4.3 to 0.5.1

### LINKED ISSUE #1149: Bump sphinx rtd theme to fix search indexing
**Description of the problem**

The search functionality for the PyGMT docs does not work for v0.3.0 onwards. I have locally confirmed that the search functionality works on the dev docs if sphinx_rtd_theme=0.4.3 is bumped up to 0.5.1 (the latest release).

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR updates sphinx_rtd_theme. Fixes #1149.

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
See https://github.com/GenericMappingTools/pygmt/pull/629 for why we pin sphinx_rtd_theme to 0.4.3

**Review by seisman — APPROVED** [review]

**Comment by meghanrjones** [comment]
I think it will be possible to use styles.css to format the parameters section as a block rather than a grid to eliminate the extra whitespace, similar to the older versions of sphinx_rtd_theme. As you mentioned in #629, it will also be necessary to check that the other configurations in style.css are compatible with 0.5.1. Should I do that now in this PR, or better to wait to do it after?

**Comment by seisman** [comment]
> > Should I do that now in this PR, or better to wait to do it after?
> 
> Better in a separate PR.

You can also create a new branch from this PR, so you can work on the new style with the latest theme.

**Review by michaelgrund — APPROVED** [review]
Good work! I think everything needed is done here.

**Review by weiji14 — APPROVED** [review]
Looks good to me. One question though, do we need to backport this somehow to the [`gh-pages`](https://github.com/GenericMappingTools/pygmt/tree/gh-pages) branch?

**Comment by core-man** [comment]
Great~ I thought it was a problem with my internet that I cannot use search.

**Comment by meghanrjones** [comment]
> Looks good to me. One question though, do we need to backport this somehow to the [`gh-pages`](https://github.com/GenericMappingTools/pygmt/tree/gh-pages) branch?

I'm not really sure. If it can be done after merging, I think it would be best to figure out if any custom CSS changes are needed before backporting. @seisman do you have any insights here?

**Pull request merged**
