### PR TITLE
Support 1d array for outcols in grdtrack and blockm functions

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR adds support for 1d array for `outcols` in grdtrack and blockm* functions by updating kwargs_to_strings arguments.

Addresses #1445.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by seisman — APPROVED** [review]

**Review by weiji14 — APPROVED** [review]
Looks ok to me, but maybe rename the title to something like "Support list inputs for outcols parameter in grdtrack and blockm functions". The "1d array" sounds like people will do `outcols=np.array([0,1])`, but the sequence comma is really just for doing `outcols=[0,1]`.

**Comment by seisman** [comment]
> The "1d array" sounds like people will do `outcols=np.array([0,1])`, but the sequence comma is really just for doing `outcols=[0,1]`.

I think `outcols=np.array([0, 1])` is also supported.

**Comment by weiji14** [comment]
> > The "1d array" sounds like people will do `outcols=np.array([0,1])`, but the sequence comma is really just for doing `outcols=[0,1]`.
> 
> I think `outcols=np.array([0, 1])` is also supported.

Yes it'll work, but a bit overkill...

Also, does this PR need the `skip-changelog` label? I don't think `outcols` was added in PyGMT v0.4.1.

**Review by michaelgrund — APPROVED** [review]

**Comment by meghanrjones** [comment]
> Looks ok to me, but maybe rename the title to something like "Support list inputs for outcols parameter in grdtrack and blockm functions". The "1d array" sounds like people will do `outcols=np.array([0,1])`, but the sequence comma is really just for doing `outcols=[0,1]`.

I think that I'll keep it as written because docstrings describe the accepted argument types as (`str or 1d array`).

**Pull request merged**
