### PR TITLE
Add link to GMT full option list for grdproject, grdsample and project

### LINKED ISSUE #1621: Missing links to upstream GMT documentation
Some functions are missing links to the official GMT docs at https://docs.generic-mapping-tools.org/latest/modules.html. Specifically, the text that says "Full option list at https://docs.generic-mapping-tools.org/latest/somegmtmodule.html"

Here are a few that I've found so far:

- [ ] [grdsample](https://www.pygmt.org/v0.5.0/api/generated/pygmt.grdsample.html)
- [ ] [grdproject](https://www.pygmt.org/v0.5.0/api/generated/pygmt.grdproject.html)
- [ ] [project](https://www.pygmt.org/v0.5.0/api/generated/pygmt.project.html)

For example, the one for `grdsample` looks like this:

https://github.com/GenericMappingTools/pygmt/blob/46fc49eb849420c385a62159e125c515e035ea6b/pygmt/src/grdsample.py#L46-L50

But it should look like this:

https://github.com/GenericMappingTools/pygmt/blob/46fc49eb849420c385a62159e125c515e035ea6b/pygmt/src/grdgradient.py#L40-L45

See https://www.pygmt.org/v0.5.0/contributing.html#editing-the-documentation-on-github for instructions on how to edit the documentation to add the missing text. Let us know if you are keen to work on this by leaving a comment below before you start :grin:

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Adds missing link to GMT doc page for `grdproject`, `grdsample` and `project`. Also standardize to use 'Full option list' across all modules (some were using 'Full parameter list' before).

Patches #1377, #1380, #1122.

Closes #1621.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by meghanrjones** [comment]
I think all options for grdimage and grdproject have aliases in PyGMT. For these and others with completed aliases, I think `Based on <module-link>` would make more sense than `Full option list at <module-link>`.

**Comment by weiji14** [comment]
> I think all options for grdimage and grdproject have aliases in PyGMT. For these and others with completed aliases, I think `Based on <module-link>` would make more sense than `Full option list at <module-link>`.

Fair point. What do others think about having fully aliased PyGMT modules use '`Based on <module-link>`'?

That said, this change is only worth it if we can make sure Paul doesn't add new options to those modules in the future :laughing:

**Comment by seisman** [comment]
> I think all options for grdimage and grdproject have aliases in PyGMT. For these and others with completed aliases, I think `Based on <module-link>` would make more sense than `Full option list at <module-link>`.

Sounds good to me.

**Review by meghanrjones — APPROVED** [review]
The current wording is fine with me.

**Review by seisman — APPROVED** [review]

**Pull request merged**
