### PR TITLE
CI: Unpin NumPy in the GMT Dev Tests workflow (#3208)

### LINKED ISSUE #2628: Failing doctest on pygmt.clib.conversion.dataarray_to_matrix with NumPy 2.0
### Description of the problem

The following doctest started failing on the GMT Dev Tests on 28 Jul 2023, previously passing on 26 Jul 2023. See https://github.com/GenericMappingTools/pygmt/actions/runs/5686923585/job/15414542417#step:16:723.

Doesn't seem to be an issue with upstream GMT, at least I don't see anything obvious in these 7 commits https://github.com/GenericMappingTools/gmt/compare/f4977110c4cddd657a34e35f6108e1dea12a1655...c94da14cee4af27d60a01f47532e649b52d923b8.

The `region` variable is created here - https://github.com/GenericMappingTools/pygmt/blob/855f6fa1b533c106d1e0fe5b68a92e1e7ef5df27/pygmt/clib/conversion.py#L88-L117 Might be related to changes in the dev version of numpy/pandas/xarray?

### Minimal Complete Verifiable Example

```python
from pygmt.datasets import load_earth_relief
# Use the global Earth relief grid with 1 degree spacing
grid = load_earth_relief(resolution="01d", registration="pixel")
matrix, region, inc = dataarray_to_matrix(grid)
print(region)
```

### Full error message

```python-traceback
=================================== FAILURES ===================================
_____________ [doctest] pygmt.clib.conversion.dataarray_to_matrix ______________
043         If the grid has more than two dimensions or variable grid spacing.
044 
045     Examples
046     --------
047 
048     >>> from pygmt.datasets import load_earth_relief
049     >>> # Use the global Earth relief grid with 1 degree spacing
050     >>> grid = load_earth_relief(resolution="01d", registration="pixel")
051     >>> matrix, region, inc = dataarray_to_matrix(grid)
052     >>> print(region)
Expected:
    [-180.0, 180.0, -90.0, 90.0]
Got:
    [np.float64(-180.0), np.float64(180.0), np.float64(-90.0), np.float64(90.0)]

/home/runner/work/pygmt/pygmt/pygmt/clib/conversion.py:52: DocTestFailure
```

### System information

Failing on:

```bash
PyGMT information:
  version: v0.9.1.dev110+gd0ca06a0
System information:
  python: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
  executable: /home/runner/micromamba/envs/pygmt/bin/python
  machine: Linux-5.15.0-1041-azure-x86_64-with-glibc2.35
Dependency information:
  numpy: 2.0.0.dev0+646.g3dd9dba09
  pandas: 2.1.0.dev0+1303.g577bb7239c
  xarray: 2023.7.1.dev18+g52f5cf1f
  netCDF4: 1.6.4
  packaging: 23.1
  contextily: 1.3.0
  geopandas: 0.13.2
  IPython: 8.15.0.dev
  rioxarray: 0.14.1
  ghostscript: 9.54.0
GMT library information:
  binary version: 6.5.0_c94da14_2023.07.27
  cores: 2
  grid layout: rows
  image layout: 
  library path: /home/runner/work/pygmt/pygmt/gmt-install-dir/lib/libgmt.so
  padding: 2
  plugin dir: /home/runner/work/pygmt/pygmt/gmt-install-dir/lib/gmt/plugins
  share dir: /home/runner/work/pygmt/pygmt/gmt-install-dir/share
  version: 6.5.0
```

Passing version:

```
PyGMT information:
  version: v0.9.1.dev110+gd0ca06a0
System information:
  python: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
  executable: /home/runner/micromamba/envs/pygmt/bin/python
  machine: Linux-5.15.0-1041-azure-x86_64-with-glibc2.35
Dependency information:
  numpy: 2.0.0.dev0+554.g0aaa5d397
  pandas: 2.1.0.dev0+1288.g1a4ac0ecb8
  xarray: 2023.7.1.dev16+gbb501ba5
  netCDF4: 1.6.4
  packaging: 23.1
  contextily: 1.3.0
  geopandas: 0.13.2
  IPython: 8.15.0.dev
  rioxarray: 0.14.1
  ghostscript: 9.54.0
GMT library information:
  binary version: 6.5.0_f497711_2023.07.25
  cores: 2
  grid layout: rows
  image layout: 
  library path: /home/runner/work/pygmt/pygmt/gmt-install-dir/lib/libgmt.so
  padding: 2
  plugin dir: /home/runner/work/pygmt/pygmt/gmt-install-dir/lib/gmt/plugins
  share dir: /home/runner/work/pygmt/pygmt/gmt-install-dir/share
  version: 6.5.0
```
Diff
```diff
Dependency information:
-  numpy: 2.0.0.dev0+554.g0aaa5d397
-  pandas: 2.1.0.dev0+1288.g1a4ac0ecb8
-  xarray: 2023.7.1.dev16+gbb501ba5
+  numpy: 2.0.0.dev0+646.g3dd9dba09
+  pandas: 2.1.0.dev0+1303.g577bb7239c
+  xarray: 2023.7.1.dev18+g52f5cf1f
GMT library information:
-  binary version: 6.5.0_f497711_2023.07.25
+  binary version: 6.5.0_c94da14_2023.07.27
```

### PR DESCRIPTION
**Pull request by seisman**
- Unpin NumPy so that NumPy 2.0.0 is installed
- Let pygmt.clib.conversion.dataarray_to_matrix return a list of `float` objects (Closes #2628)

### CODE REVIEW

**Comment by seisman** [comment]
The "GMT Dev Tests" workflow passed four days ago (https://github.com/GenericMappingTools/pygmt/actions/runs/9508848053/job/26210865246) but suddenly failed 12 hours ago (https://github.com/GenericMappingTools/pygmt/actions/runs/9540235948/job/26291686980).

There are no changed on the GMT side, so it's likely due to a broken library installed by conda-forge. 

I think we can go with this PR and find out why the workflow fails on Windows later.

**Review by weiji14 — APPROVED** [review]
Thanks @seisman, I think we can go with this to handle compatibility between NumPy 1.x and 2.0.

Btw, do you want to bump the NumPy version on `ci_tests.yml` after this? Or we keep testing NumPy 1.26 for a few more months?

https://github.com/GenericMappingTools/pygmt/blob/3719474499b1d233e372d6d21fdfd1ce88f2f383/.github/workflows/ci_tests.yaml#L78

**Comment by seisman** [comment]
> Btw, do you want to bump the NumPy version on `ci_tests.yml` after this? Or we keep testing NumPy 1.26 for a few more months?

Tried in 3fc015642a332ed3735df1435296cf8e1de1e8fe, but there are dependency issues
https://github.com/GenericMappingTools/pygmt/actions/runs/9537393685/job/26285444415?pr=3226. It seems some packages are not updated to work with NumPy 2.0

**Comment by seisman** [comment]
> > Btw, do you want to bump the NumPy version on `ci_tests.yml` after this? Or we keep testing NumPy 1.26 for a few more months?
> 
> Tried in [3fc0156](https://github.com/GenericMappingTools/pygmt/commit/3fc015642a332ed3735df1435296cf8e1de1e8fe), but there are dependency issues https://github.com/GenericMappingTools/pygmt/actions/runs/9537393685/job/26285444415?pr=3226. It seems some packages are not updated to work with NumPy 2.0

I think the dependency issue has been resolved. See https://github.com/GenericMappingTools/pygmt/pull/3292.

**Pull request merged**
