### PR TITLE
Add Wei Ji to AUTHORS.md

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Requesting [write access](https://help.github.com/en/articles/repository-permission-levels-for-an-organization) to the PyGMT repository.

There's still a lot of [open pull requests](https://github.com/GenericMappingTools/pygmt/pulls?q=is%3Aopen+is%3Apr) from the start of the year (`makecpt`, `grdtrack`, etc) I'd like to merge in for my research work, and also for the FOSS4G Oceania workshop (#317) that's coming up in November 2019. Understandable that stabilizing the core GMT6 release is a priority now, but I'd like to take on a more active role here in PyGMT, working towards a 0.1.0 release soon!

### CODE REVIEW

**Comment by weiji14** [comment]
Hi @seisman, do you think you can approve this as it's been more than ten days and @leouieda doesn't seem to have responded.

**Comment by seisman** [comment]
Thanks for your contributions to the project! I think it's OK to add you to the AUTHORS.md. As for the write access, I think we still need @leouieda to decide.

**Comment by weiji14** [comment]
Ok, let's see if he responds next week. I've got a growing list of things I'd like to contribute into PyGMT and it's sitting in way too many branches at the moment :laughing:

**Comment by leouieda** [comment]
@weiji14 @seisman sorry for the long disappearance :slightly_smiling_face: I'm very happy to have Wei on board! I'll add you to the @GenericMappingTools/python team so you'll have full write access to this repo.

**Comment by weiji14** [comment]
Thanks @leouieda :tada:, hope your new lecturer position is going well too :smile:

**Pull request merged**
