### PR TITLE
WIP: Refactor test_basemap_polar to use mpl_image_compare and track png files in dvc

### PR DESCRIPTION
**Pull request by seisman**
Testing #1036.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by weiji14** [comment]
> I just added a new image to my testing branch (commit [b8bdb7c](https://github.com/GenericMappingTools/pygmt/commit/b8bdb7c20008f24f7e27b9c765c5fe77293baf4d) in #1071). However, I can't preview the image in DAGsHub: https://dagshub.com/GenericMappingTools/pygmt/src/fix-test-basemap-polar/pygmt/tests/baseline

Did you do `dvc push`? Maybe try the sync button at the top of the page?

**Comment by seisman** [comment]
> Did you do `dvc push`? 

Yes, I already did the `dvc push`, and it said one file is uploaded. So the CI test should work (but it will fail because I generated the image using GMT 6.2.0).

> Maybe try the sync button at the top of the page?

I'm afraid we have to push the sync button to preview the image. Not sure if our collaborators can also push the button.

**Comment by seisman** [comment]
> > Did you do `dvc push`?
> 
> Yes, I already did the `dvc push`, and it said one file is pushed. So the CI test should work (but it will fail because I generated the image using GMT 6.2.0).

The image is correctly downloaded using `dvc pull`. The tests all pass, perhaps there are no changes for this image between GMT 6.1.1 and GMT 6.2.0

> > Maybe try the sync button at the top of the page?
> 
> I'm afraid we have to push the sync button to preview the image. Not sure if our collaborators can also push the button.

Did you push the sync button? I don't, but now I can preview the image (about 10 minutes after I run the `dvc push` command):

image

**Comment by weiji14** [comment]
> Did you push the sync button? I don't, but now I can preview the image (about 10 minutes after I run the dvc push command):

Yeah I pushed it. I thought you did but didn't see anything when I refreshed the page, so I just pressed it...

> > Maybe try the sync button at the top of the page?
> 
> I'm afraid we have to push the sync button to preview the image. Not sure if our collaborators can also push the button.

They should be able to push the button, that DAGsHub repo is just a clone of the GitHub repo so shouldn't have any permissions issue (all public anyway).

Another way I've thought about to preview the image is to use `cml-publish` at https://github.com/iterative/setup-cml to publish the image diff as a GitHub comment in the PR. It's originally intended for tracking machine learning graphs but I think there's a way to hack it to work for our image testing use case. But 1) should finish #1037 first and 2) this will need some experimenting.

**Comment by seisman** [comment]
> They should be able to push the button, that DAGsHub repo is just a clone of the GitHub repo so shouldn't have any permissions issue (all public anyway).

OK. At least we can pull the images and review them.

**Pull request closed without merging**
