### PR TITLE
Exclude DVC files from source/binary distributions

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

See https://github.com/GenericMappingTools/pygmt/issues/1086 for context.

This PR excludes all the `*.dvc` files from the source/binary distributions to reduce the tarball sizes. The source tarball size is reduced from 251K to 238K.

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by michaelgrund — APPROVED** [review]

**Review by yvonnefroehlich — APPROVED** [review]

**Comment by seisman** [comment]
Ping @weiji14 to have a final review since he is more experienced with DVC and python packaging.

**Comment by weiji14** [comment]
Probably should still archive the `*.dvc` files somewhere. Could you modify the `release-basline-images.yml` workflow to also save the `*.dvc` files on release? From #1317, it is only saving the `*.png` files, and not the `*.dvc` files.

**Comment by seisman** [comment]
> Probably should still archive the `*.dvc` files somewhere.

These `*.dvc` files are still available in the source code tarballs created by GitHub releases (e.g., see https://github.com/GenericMappingTools/pygmt/releases/tag/v0.9.0).

**Review by weiji14 — APPROVED** [review]
> > Probably should still archive the `*.dvc` files somewhere.
> 
> These `*.dvc` files are still available in the source code tarballs created by GitHub releases (e.g., see https://github.com/GenericMappingTools/pygmt/releases/tag/v0.9.0).

Ah yes, then should be ok then! Good to have a smaller source tarball on PyPI.

**Pull request merged**
