### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Python 3.11 has been released on Oct. 24, 2022, changelog is at [docs.python.org/3.11/whatsnew/3.11.html](https://docs.python.org/3.11/whatsnew/3.11.html). 

Previous PRs for Python 3.10 are https://github.com/GenericMappingTools/pygmt/pull/1591 and https://github.com/GenericMappingTools/pygmt/pull/1577.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by weiji14** [comment]
Not sure why the `mamba install` step fails at https://github.com/GenericMappingTools/pygmt/actions/runs/3326717710/jobs/5525427951#step:5:63 without any useful error message, so I tried testing locally:

```bash
mamba create --name pygmt python=3.11
mamba activate pygmt
mamba install gmt=6.4.0 numpy=1.23 pandas xarray netCDF4 packaging geopandas ipython build dvc make pytest>=6.0 pytest-cov pytest-doctestplus pytest-mpl sphinx-gallery
```
which also crashed with no error :sweat_smile: I think there are some python 3.11 migrations still ongoing (see https://conda-forge.org/status/#python311), so maybe wait for a few more days.

**Comment by weiji14** [comment]
I figured out why no error messages were raised. It's because of these lines:

https://github.com/GenericMappingTools/pygmt/blob/6149c53dd5e30635a9ff482f5a98e625ed4ad08d/.github/workflows/ci_tests.yaml#L95

https://github.com/GenericMappingTools/pygmt/blob/6149c53dd5e30635a9ff482f5a98e625ed4ad08d/.github/workflows/ci_tests_legacy.yaml#L68

Should be using `'pytest>=6.0'` instead of `pytest>=6.0`, otherwise the outputs go into a file called `=6.0` :sweat_smile:

**Comment by weiji14** [comment]
Seems like `dvc` is waiting on https://github.com/conda-forge/omegaconf-feedstock/pull/40#issuecomment-1294669062, gonna see it's possible to make `omegaconf` noarch to unblock this.

dvc package dependent on omegaconf

**Comment by weiji14** [comment]
Yeah, so `dvc` is now noarch :tada:, but `mamba` is stuck trying to finding a solution satisfying `python=3.11` :joy:. Still need to wait for `omegaconf>=2.2.4` I think. The dependency chain is `dvc` -> `hydra-core` -> `omegaconf`, and because `omegaconf` on conda-forge is currently pinned to `python <3.11`, the CI workflows using `dvc` won't work :sob:

**Comment by weiji14** [comment]
The `dvc` -> `hydra-core` -> `omegaconf` dependency chain should be ok now. I think it's the `geopandas` -> `fiona` part which still needs some love. Specifically, need to wait for GDAL 3.6 builds of fiona, see https://github.com/conda-forge/fiona-feedstock/pull/203?

**Comment by weiji14** [comment]
> The `dvc` -> `hydra-core` -> `omegaconf` dependency chain should be ok now. I think it's the `geopandas` -> `fiona` part which still needs some love.
> `Encountered problems while solving: - package dvc-2.36.0-pyhd8ed1ab_1 requires hydra-core >=1.1.0, but none of the providers can be installed`

Spoke too soon. We actually need `hydra-core` to relax it's dependency pin to use `omegaconf=2.3` to be installable with Python 3.11. Issue being tracked at https://github.com/facebookresearch/hydra/issues/2510.

Do you want to wait, or split this PR into 2 (as was done with Python 3.10) - one for the files that don't use `dvc`, and one for the CI workflows that use `dvc`?

**Comment by seisman** [comment]
> Do you want to wait, or split this PR into 2 (as was done with Python 3.10) - one for the files that don't use `dvc`, and one for the CI workflows that use `dvc`?

I feel it makes more sense to wait, because we can't say that we support Python 3.11 without running the full tests (which requires dvc).

**Comment by maxrjones** [comment]
@weiji14 great work getting all those package conflicts cleaned up! 🚀 🎉

**Review by weiji14 — APPROVED** [review]
> @weiji14 great work getting all those package conflicts cleaned up! rocket tada

Yes, finally! Those `dvc` dependencies with hard upper pins were painful :slightly_smiling_face: We're at ~2months since Python 3.11 was released so not too bad, about the same as Python 3.10 last year in #1577. I'm hoping that Python 3.12 will be smoother since `dvc` is noarch now :pray:

**Pull request merged**
