### PR TITLE
Remove the unused pygmt.test() function

### PR DESCRIPTION
**Pull request by seisman**
The `pygmt.test()` function is not used and can be removed.

Closes https://github.com/GenericMappingTools/pygmt/issues/2633

### CODE REVIEW

**Comment by seisman** [comment]
I'm fine with merging this PR before or after the v0.10.0 release.

**Review by michaelgrund — APPROVED** [review]

**Comment by michaelgrund** [comment]
> I'm fine with merging this PR **before** or **after** the v0.10.0 release.

Would merge it before.

**Review by weiji14 — APPROVED** [review]
Ok, do we label this under maintenance or deprecation?

**Comment by seisman** [comment]
"Deprecation" makes more sense.

**Pull request merged**
