### PR TITLE
Bump minimum required GMT from 6.0.0rc5 to 6.0.0

### LINKED ISSUE #362: Update to GMT 6.0.0
GMT 6.0.0 is released, and the conda-forge package has been updated to 6.0.0. 

Install GMT6 via conda is much easier now, and the `conda-forge/label/dev` channel is no longer needed.
```
conda install gmt -c conda-forge
```

We should update the minimum required GMT version to 6.0.0, installation instructions, and also the CI settings.

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

GMT6 is finally released, so we can simplify our conda installation steps and update the documentation accordingly.

TODO:
- [x] Use GMT 6.0.0 from the main conda-forge channel in our CI scripts and config files
- [x] Update documentation to indicate GMT6 is released!
- [x] Mention new [GMT Community Forum](https://forum.generic-mapping-tools.org/)

Fixes #362, Supersedes #351 

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

### CODE REVIEW

**Comment by weiji14** [comment]
Team, I need to rush off now but will be back in a couple of hours. Have a look to see if I've missed out on anything. Website preview at https://pygmt-git-fork-weiji14-gmt600.gmt.now.sh/

**Comment by weiji14** [comment]
Sure, had the same thought actually. Do we still want to keep gitter around for a while?

**Comment by weiji14** [comment]
Ok, I've updated most of the obvious contact links to the new discourse forum but kept the old gitter.im on the main README for now. There's actually a surprising amount of webhooks to gitter (which links to the old gmt-python gitter chat instead of pygmt...), and stuff like PyPI contact info I'm cautious not to touch. Should open up a new PR to discuss about purging those (or not). Will merge this in as is for now though.

**Comment by leouieda** [comment]
Hi @weiji14 and @seisman, thanks for keeping things going! I would just like to ask if you could slow down a little bit. I've been having very limited time to work on this but I think PRs should be discussed, particularly when we have to consider wording choices or introduction of new functions. It's easy to add things but changing or removing them later can be a huge hassle if we're being good to our users and not breaking things. So I prefer to think deeply before merging. As a courtesy, please allow for at least 2-3 days for discussion before rushing to merge (unless it's something trivial). Thanks!

**Comment by leouieda** [comment]
Sorry if this came out as ungrateful. I really really appreciate all that you two have done (and continue to do) for the project! I don't want to be a bottle neck on most things and you two have admin rights to the repository for a reason.

**Comment by weiji14** [comment]
Noted :ok_hand:. I definitely got a bit carried away recently, especially with GMT6 being released (got excited after have been waiting for almost a year!). That's not really an excuse though, and I do apologize for my haste. The 2-3 days cooldown sounds good, since we'll need to appreciate the different timezones and work-life balance of our diverse contributors going forward :fast_forward:.

**Pull request merged**
