### PR TITLE
Gallery example "Clipping grid values": Add annotations to frames

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

This PR aims to add annotations to the frames of the maps in the gallery example `Clipping grid values`:

| without annotations | with annotations |
| --- | --- |
|  grdclip_WITHOUT_Baf | grdclip_WITH_Baf |

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
There seem to be differences in the Style Checks, especially regarding `pylint`:
```
Run make lint
pylint pygmt doc/conf.py
************* Module conf
doc/conf.py:1:0: R0401: Cyclic import (pygmt -> pygmt.src -> pygmt.src.timestamp) (cyclic-import)
doc/conf.py:1:0: R0401: Cyclic import (pygmt -> pygmt.src -> pygmt.src.ternary) (cyclic-import)
doc/conf.py:1:0: R0401: Cyclic import (pygmt -> pygmt.figure -> pygmt.src.timestamp) (cyclic-import)
doc/conf.py:1:0: R0401: Cyclic import (pygmt -> pygmt.figure -> pygmt.src.ternary) (cyclic-import)

-----------------------------------
Your code has been rated at 9.99/10

make: *** [Makefile:79: lint] Error 8
Error: Process completed with exit code 2.
```

**Comment by seisman** [comment]
The style failures are caused by the new pylint release https://github.com/pylint-dev/pylint/releases/tag/v3.0.0.

**Comment by seisman** [comment]
Why make the changes? The old figure looks good to me.

**Comment by yvonnefroehlich** [comment]
> Why make the changes? The old figure looks good to me.

I feel it would be better to have map frames with annotations.

**Review by seisman — APPROVED** [review]

**Pull request merged**
