### PR TITLE
Refresh Code of Conduct from v1.4 to v2.0

### LINKED ISSUE #672: Refreshing our Code of Conduct to v2.0
**Description of the desired feature**

Our original Code of Conduct was added 3 years ago at https://github.com/GenericMappingTools/pygmt/commit/5123e401c9a9bbff9db46073a79e17b94aa67151 by @leouieda on 22 July 2017, and is based on version **1.4** of the Contributor Covenant (see https://www.contributor-covenant.org/version/1/4/code-of-conduct/).

A lot has happened to the world since then, and it is time, as a (bigger) community :people_holding_hands:, to put a bit of time into refreshing the document. There is a draft Pull Request to update our Code of Conduct to v2.0 at #673, but **please** take the time to voice your opinion on what you would like (or not like) PyGMT to look like - in terms of communication style - for the next 3 years (or so).

In particular, I'm hoping to hear what we can do to recruit a broader range of contributors that reflects the **diversity** of the geosciences community. We're doing good on the international front with people spread out over different continents/timezones, but there are many other dimensions like race, gender, etc, which definitely needs more work. That's enough of me talking, let's hear from some other folks :smile:

References:
- https://www.contributor-covenant.org/version/2/0/code_of_conduct/
- https://github.com/ContributorCovenant/contributor_covenant/pull/709

**Are you willing to help implement and maintain this feature?** Yes

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Refreshes our code of conduct from v1.4 to v2.0, and also add a [Contributor Covenant](code_of_conduct.md) badge to the main README.md. Community discussion can take place at #672.

Changes (copied from https://github.com/ContributorCovenant/contributor_covenant/blob/29000ea9977e75b76189335f376a42a833972433/changelog#L19-L26):

- Emphasizes 'community' over 'project' scope, effectively merging the Community Covenant into the Contributor Covenant
- Adds expectation about accepting responsibility and apologizing to those affected by mistakes, and learning from the experience to the list
- Adds sexual attention and advances of any kind as unacceptable behavior example
- Moves enforcement responsibilities from project maintainers to community leaders
- Adds responsibility to communicate reasons for moderation decisions when removing, editing, or rejecting contributions not aligned to the Code of Conduct
- Requires community leaders to respect privacy and security of the reporter of any incident, not just confidentiality
- Provides a template for code of conduct enforcement

The text is copied over from https://www.contributor-covenant.org/version/2/0/code_of_conduct/. Feel free to tweak any of the points if there is anything you feel should be in (or not in) the document.

Fixes #672

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Notes**

- You can write `/format` in the first line of a comment to lint the code automatically

### CODE REVIEW

**Comment by seisman** [comment]
Looks good to me, but let's hear more from @GenericMappingTools/python @GenericMappingTools/python-contributors

**Review by liamtoney — APPROVED** [review]

**Review by leouieda — APPROVED** [review]
Looks great @weiji14! I quite like v2.0, in particular the enforcement guidelines. Gives the CoC a more concrete feeling.

**Review by seisman — APPROVED** [review]
Looks OK to merge.

**Comment by weiji14** [comment]
Cool! I'll leave it open for a few more days (before v0.2.1 #665 is about to be released) in case anyone else wants to voice their opinion.

**Pull request merged**
