### PR TITLE
Convert line breaks from DOS to UNIX

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

It seems @willschlitzer is developing PyGMT under Windows, and the new
files he created have DOS-style line breaks.

To keep the consistency in the whole project, I convert all these files
to UNIX-style line breaks using `dos2unix`. I don't know how git
and github handles line breaks, but I can't see the changes 
in the diff view.

I also removed the `x` permission of these files.

Perhaps we also need a style check for line breaks?

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Notes**

- You can write `/format` in the first line of a comment to lint the code automatically

### CODE REVIEW

**Comment by willschlitzer** [comment]
Not sure on what's causing this; I'm using PyCharm Professional on Ubuntu 20.04

**Comment by weiji14** [comment]
Wow, good catch, would not have spotted that. Could you add the style check in this PR too if it's not too much work?

@willschlitzer, try https://www.jetbrains.com/help/pycharm/configuring-line-endings-and-line-separators.html

**Comment by weiji14** [comment]
So, chicken and egg question, do we merge this PR first, or #736 with the new style check?

Also, should we have a style check for ensuring there's no executable 'x' permissions (755)?

**Comment by seisman** [comment]
> So, chicken and egg question, do we merge this PR first, or #736 with the new style check?

We can merge this PR first, and then #736.

> Also, should we have a style check for ensuring there's no executable 'x' permissions (755)?

Sounds a good idea.

**Review by weiji14 — APPROVED** [review]

**Pull request merged**
