### PR TITLE
Replace underscores with hyphens in projection gallery file names.

### PR DESCRIPTION
**Pull request by willschlitzer**
As discussed in #995, the project is inconsistent with under underscores or hyphens in file names, and advocates switching every file name to use hyphens. This PR makes that change for the projection gallery examples.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by core-man** [comment]
Shall we add this rule in [CONTRIBUTING.md](https://github.com/GenericMappingTools/pygmt/blob/master/CONTRIBUTING.md)?

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/pygmt/tree/master/examples/projections/table

Also need to update all the `:doc:` references in this file.

**Comment by willschlitzer** [comment]
> https://github.com/GenericMappingTools/pygmt/tree/master/examples/projections/table
> 
> Also need to update all the `:doc:` references in this file.

Fixed in 4b6fb8d

**Comment by seisman** [comment]
Close this one, as we'll use underscores (https://github.com/GenericMappingTools/pygmt/pull/1034#discussion_r591208655).

**Pull request closed without merging**
