### PR TITLE
Bump GMT version from 6.2.0rc1 to 6.2.0rc2 in CI

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

Second release candidate of Generic Mapping Tools v6.2.0 at https://github.com/GenericMappingTools/gmt/releases/tag/6.2.0rc2.

**Note**: This PR also temporarily stops `geopandas` from being installed in the main test suite, see https://github.com/GenericMappingTools/pygmt/pull/1290#issuecomment-847495768 for the rationale.

Related to #1289, Supersedes #1218

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by weiji14** [comment]
The Python 3.9 / NumPy 1.20 build can't get past the install step (see https://github.com/GenericMappingTools/pygmt/pull/1290/checks?check_run_id=2661062442#step:5:1). I think this is due to a package conflict with `gmt` and `geopandas`. Specifically, the `gmt=6.2.0rc2` conda package is linked to GDAL 3.3, but `geopandas` requires `fiona` which only has packages up to GDAL 3.2. We'll need to wait for https://github.com/conda-forge/fiona-feedstock/pull/179 before proceeding.

**Comment by seisman** [comment]
Perhaps we can temporarily remove "geopands" so we can proceed?

**Comment by weiji14** [comment]
> Perhaps we can temporarily remove "geopands" so we can proceed?

Not a big fan of this idea, but yeah we might have to. What I might do is to remove geopandas from ci_tests.yaml, but install it in ci_tests_dev.yaml (while pinning to GDAL 3.2) so that we have some tests using `geopandas` at least (for coverage).

**Review by seisman — APPROVED** [review]
Looks good if all tests pass.

**Comment by weiji14** [comment]
> Looks good if all tests pass.

Well, the tests won't all pass because we need to update 24 of them :rofl: But I'm assuming we'll update those in separate PRs later :innocent:

**Pull request merged**
