### PR TITLE
NEP29: Set minimum required version to NumPy 1.19+

### PR DESCRIPTION
**Pull request by michaelgrund**
**Description of proposed changes**

Following NEP29 policy where NumPy 1.18 is to be dropped on or after Dec. 22, 2021 (in a minor version increment, i.e. for PyGMT v0.6.0). Bumps minimum supported NumPy version to 1.19 in the setup.py, requirements.txt and environment.yml files. Also update installation documentation and set CI tests to run on NumPy 1.19.

xref: #1430

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by seisman — APPROVED** [review]
Looks good to me.

@michaelgrund Better to change the title to "NEP29: Set minimum required version to NumPy 1.19+" following previous PRs #1430, #1074

**Review by weiji14 — APPROVED** [review]
Yep, agree with @seisman's statement to change the title above. Also, we'll need to update the branch protection rules at https://github.com/GenericMappingTools/pygmt/settings/branches to require `Python 3.7 / NumPy 1.19` before merging.

**Comment by michaelgrund** [comment]
> Looks good to me.
> 
> @michaelgrund Better to change the title to "NEP29: Set minimum required version to NumPy 1.19+" following previous PRs #1430, #1074

Thanks 😉

**Comment by michaelgrund** [comment]
> Yep, agree with @seisman's statement to change the title above. Also, we'll need to update the branch protection rules at https://github.com/GenericMappingTools/pygmt/settings/branches to require `Python 3.7 / NumPy 1.19` before merging.

Good to know, that needs to be done by an owner, correct @weiji14 ?

**Comment by weiji14** [comment]
> > Yep, agree with @seisman's statement to change the title above. Also, we'll need to update the branch protection rules at https://github.com/GenericMappingTools/pygmt/settings/branches to require `Python 3.7 / NumPy 1.19` before merging.
> 
> Good to know, that needs to be done by an owner, correct @weiji14 ?

Yep, just someone with admin privileges. I've done it already. Should be good to merge once status checks all pass.

**Comment by michaelgrund** [comment]
> > > Yep, agree with @seisman's statement to change the title above. Also, we'll need to update the branch protection rules at https://github.com/GenericMappingTools/pygmt/settings/branches to require `Python 3.7 / NumPy 1.19` before merging.
> > 
> > 
> > Good to know, that needs to be done by an owner, correct @weiji14 ?
> 
> Yep, just someone with admin privileges. I've done it already. Should be good to merge once status checks all pass.

Great, thanks 😉

**Pull request merged**
