### PR TITLE
Changes to speed up Earth relief and regions tutorials

### LINKED ISSUE #825: Improve some tutorials to speed up the Continuous Documentation
This is a summary of running time of the PyGMT tutorials and examples:

```
computation time summary:
    - ../examples/tutorials/regions.py:                                   11.34 sec   0.0 MB
    - ../examples/tutorials/3d-perspective-image.py:                      10.06 sec   0.0 MB
    - ../examples/tutorials/frames.py:                                     6.56 sec   0.0 MB
    - ../examples/tutorials/lines.py:                                      5.86 sec   0.0 MB
    - ../examples/gallery/grid/grdview_surface.py:                         5.47 sec   0.0 MB
    - ../examples/tutorials/earth-relief.py:                               5.32 sec   0.0 MB
    - ../examples/tutorials/text.py:                                       4.63 sec   0.0 MB
    - ../examples/tutorials/contour-map.py:                                3.88 sec   0.0 MB
    - ../examples/tutorials/coastlines.py:                                 3.07 sec   0.0 MB
    - ../examples/tutorials/plot.py:                                       2.58 sec   0.0 MB
    - ../examples/projections/azim/azim_general_perspective.py:            2.36 sec   0.0 MB
    - ../examples/tutorials/first-figure.py:                               1.71 sec   0.0 MB
    - ../examples/tutorials/configuration.py:                              1.58 sec   0.0 MB
    - ../examples/gallery/coast/borders.py:                                1.45 sec   0.0 MB
    - ../examples/gallery/plot/scatter3d.py:                               1.23 sec   0.0 MB
    - ../examples/gallery/grid/track_sampling.py:                          1.18 sec   0.0 MB
    - ../examples/projections/cyl/cyl_cassini.py:                          0.99 sec   0.0 MB
    - ../examples/projections/azim/azim_equidistant.py:                    0.93 sec   0.0 MB
    - ../examples/gallery/line/line-custom-cpt.py:                         0.91 sec   0.0 MB
    - ../examples/gallery/coast/shorelines.py:                             0.89 sec   0.0 MB
    - ../examples/projections/conic/conic_albers.py:                       0.85 sec   0.0 MB
    - ../examples/gallery/coast/land_and_water.py:                         0.83 sec   0.0 MB
    - ../examples/gallery/plot/image.py:                                   0.82 sec   0.0 MB
    - ../examples/gallery/plot/scatter.py:                                 0.73 sec   0.0 MB
    - ../examples/projections/cyl/cyl_universal_transverse_mercator.py:    0.70 sec   0.0 MB
    - ../examples/gallery/plot/logo.py:                                    0.67 sec   0.0 MB
    - ../examples/projections/azim/azim_gnomonic.py:                       0.67 sec   0.0 MB
    - ../examples/projections/misc/misc_van_der_grinten.py:                0.66 sec   0.0 MB
    - ../examples/projections/nongeo/polar.py:                             0.66 sec   0.0 MB
    - ../examples/projections/azim/azim_orthographic.py:                   0.66 sec   0.0 MB
    - ../examples/projections/cyl/cyl_miller.py:                           0.65 sec   0.0 MB
    - ../examples/projections/azim/azim_general_stereographic.py:          0.65 sec   0.0 MB
    - ../examples/projections/misc/misc_winkel_tripel.py:                  0.64 sec   0.0 MB
    - ../examples/projections/nongeo/cartesian_logarithmic.py:             0.64 sec   0.0 MB
    - ../examples/projections/conic/conic_lambert.py:                      0.63 sec   0.0 MB
    - ../examples/gallery/plot/legend.py:                                  0.62 sec   0.0 MB
    - ../examples/gallery/line/linestyles.py:                              0.61 sec   0.0 MB
    - ../examples/projections/cyl/cyl_equal_area.py:                       0.61 sec   0.0 MB
    - ../examples/projections/cyl/cyl_transverse_mercator.py:              0.58 sec   0.0 MB
    - ../examples/projections/conic/polyconic.py:                          0.58 sec   0.0 MB
    - ../examples/projections/nongeo/cartesian_power.py:                   0.57 sec   0.0 MB
    - ../examples/projections/cyl/cyl_equidistant.py:                      0.57 sec   0.0 MB
    - ../examples/projections/misc/misc_eckertVI.py:                       0.57 sec   0.0 MB
    - ../examples/gallery/plot/colorbar.py:                                0.56 sec   0.0 MB
    - ../examples/gallery/plot/points.py:                                  0.56 sec   0.0 MB
    - ../examples/projections/cyl/cyl_mercator.py:                         0.55 sec   0.0 MB
    - ../examples/projections/misc/misc_eckertIV.py:                       0.55 sec   0.0 MB
    - ../examples/projections/misc/misc_hammer.py:                         0.55 sec   0.0 MB
    - ../examples/projections/azim/azim_lambert.py:                        0.55 sec   0.0 MB
    - ../examples/projections/nongeo/cartesian_linear.py:                  0.55 sec   0.0 MB
    - ../examples/gallery/plot/points-transparency.py:                     0.55 sec   0.0 MB
    - ../examples/projections/cyl/cyl_stereographic.py:                    0.55 sec   0.0 MB
    - ../examples/projections/misc/misc_robinson.py:                       0.55 sec   0.0 MB
    - ../examples/projections/misc/misc_sinusoidal.py:                     0.54 sec   0.0 MB
    - ../examples/projections/misc/misc_mollweide.py:                      0.53 sec   0.0 MB
    - ../examples/projections/conic/conic_equidistant.py:                  0.53 sec   0.0 MB
    - ../examples/gallery/plot/meca.py:                                    0.53 sec   0.0 MB
    - ../examples/gallery/plot/datetime-inputs.py:                         0.46 sec   0.0 MB
    - ../examples/gallery/plot/multi-parameter-symbols.py:                 0.46 sec   0.0 MB
```

For example, `examples/tutorials/regions.py` takes more than 10 seconds. I guess it's slow because the two global examples plot borders of all countries. However, these borders are not necessary here, as we are showing how to set regions in the tutorial.

I don't check other tutorials, but I believe some tutorials, especially the slowest ones can be much faster if we are more careful about choosing the arguments.

### PR DESCRIPTION
**Pull request by willschlitzer**
Makes the changes suggested for `regions.py` and `earth-relief.py` to reduce the time to generate the tutorials. This PR removes the internal national borders in `regions.py` and changes the land color to dark gray. It also changes the `registration` for the loaded Earth relief grid to "gridline" because that is the cached version.

Fixes #825

**Reminders**

- [X] Run `make format` and `make check` to make sure the code follows the style guide.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by willschlitzer** [comment]
``` 
computation time summary:
    - ../examples/tutorials/3d-perspective-image.py:                      11.75 sec   0.0 MB
    - ../examples/tutorials/regions.py:                                   10.57 sec   0.0 MB
    - ../examples/tutorials/frames.py:                                     6.65 sec   0.0 MB
    - ../examples/tutorials/lines.py:                                      6.62 sec   0.0 MB
    - ../examples/tutorials/earth-relief.py:                               6.43 sec   0.0 MB
    - ../examples/gallery/grid/grdview_surface.py:                         6.32 sec   0.0 MB
    - ../examples/tutorials/text.py:                                       4.93 sec   0.0 MB
    - ../examples/tutorials/contour-map.py:                                4.61 sec   0.0 MB
    - ../examples/tutorials/coastlines.py:                                 3.60 sec   0.0 MB
 ```

@seisman This doesn't appear to have changed the times to build the documentation; any ideas on how to improve it?

**Comment by weiji14** [comment]
Might need to merge in the change from #866 first to use the cache properly.

**Comment by willschlitzer** [comment]
```
computation time summary:
    - ../examples/tutorials/3d-perspective-image.py:                      10.86 sec   0.0 MB
    - ../examples/tutorials/regions.py:                                   10.02 sec   0.0 MB
    - ../examples/tutorials/frames.py:                                     6.39 sec   0.0 MB
    - ../examples/tutorials/lines.py:                                      5.99 sec   0.0 MB
    - ../examples/gallery/grid/grdview_surface.py:                         5.84 sec   0.0 MB
    - ../examples/tutorials/earth-relief.py:                               5.63 sec   0.0 MB
    - ../examples/tutorials/text.py:                                       4.36 sec   0.0 MB
    - ../examples/tutorials/contour-map.py:                                4.22 sec   0.0 MB
    - ../examples/tutorials/coastlines.py:                                 3.27 sec   0.0 MB
    - ../examples/tutorials/inset.py:                                      2.96 sec   0.0 MB
    - ../examples/projections/azim/azim_general_perspective.py:            2.69 sec   0.0 MB
    - ../examples/tutorials/plot.py:                                       2.48 sec   0.0 MB
    - ../examples/tutorials/first-figure.py:                               1.70 sec   0.0 MB
    - ../examples/tutorials/configuration.py:                              1.65 sec   0.0 MB
    - ../examples/gallery/plot/inset.py:                                   1.39 sec   0.0 MB
    - ../examples/gallery/grid/track_sampling.py:                          1.11 sec   0.0 MB
    - ../examples/gallery/coast/borders.py:                                1.08 sec   0.0 MB
    - ../examples/projections/cyl/cyl_cassini.py:                          0.98 sec   0.0 MB
 ```
Merging the changes from #866 doesn't seem to have sped up the tests.

**Comment by seisman** [comment]
I'm afraid the key reason for the slow execution time is because there are too many figures in these tutorials (7 for 3d perspective figure and 11 for regions).

For example, in the 3d perspective figure, can we merge the last few (~3) figures into one figure?

**Comment by seisman** [comment]
Here is what we can do to improve the 3D respective tutorial:

1. Use a lower resolution earth relief grid (currently impossible, because lower-resolution grids don't support the `region` argument yet)
2. Merge the 2nd and the 3rd figures
3. Merge the last three figures (still easy to understand what `contourpen`, `colorbar` and `perspective` do).

**Comment by willschlitzer** [comment]
Closing this PR due to creating multiple branches and pushing them; discussion/further edits will be at #871

**Pull request closed without merging**
