### PR TITLE
Add guidelines for types of tests to write

### PR DESCRIPTION
**Pull request by willschlitzer**
As discussed in #771, this PR adds recommended guidelines to CONTRIBUTING.md for types of tests to write. It emphasizes testing on Python-specific code over GMT aliases and functions.

### CODE REVIEW

**Comment by willschlitzer** [comment]
@weiji14 @seisman I added the recommendations we discussed, but I'm still a little confused on how we should address testing aliases and the basic creation of plots. I could see how someone could get confused looking at the testing guidelines, which don't recommend focusing on GMT aliases and functions, and then seeing that the majority of test files focus on testing the creation of plots and how the aliases work.

**Comment by seisman** [comment]
> then seeing that the majority of test files focus on testing the creation of plots and how the aliases work.

There may be some misunderstanding here. Could you point out some tests which you think don't follow the guidelines?

**Comment by willschlitzer** [comment]
@seisman I probably should have specified that I'm looking at the plotting functions, as the majority of the tests that work with GMT under the hood don't focus on testing plotting aliases. Looking at `test_colorbar.py` there are a lot of tests passing different location inputs, `test_coast.py` has a lot of tests for the different arguments (some of which I've written), `test_basemap.py` has numerous tests creating different types of plots. I'm not opposed to these types of tests, but I want to avoid any confusion with the guidelines suggesting that those types of tests are unnecessary.

I

**Comment by seisman** [comment]
> @seisman I probably should have specified that I'm looking at the plotting functions, as the majority of the tests that work with GMT under the hood don't focus on testing plotting aliases. Looking at `test_colorbar.py` there are a lot of tests passing different location inputs, `test_coast.py` has a lot of tests for the different arguments (some of which I've written), `test_basemap.py` has numerous tests creating different types of plots. I'm not opposed to these types of tests, but I want to avoid any confusion with the guidelines suggesting that those types of tests are unnecessary.

I see your points. Some of the tests were written years ago, and we didn't have any guidelines at that time (we're still learning  to make the project better and developer-friendly). 

If you look at the core codes of the `colorbar()` function, you will realize that the colorbar wrapper is pretty simple and almost has no Python-specific codes. However, we still need/want to add a few tests to make sure `colorbar()` works as expected. But I agree that some of the tests may be unnecessary.

**Review by seisman — APPROVED** [review]

**Pull request merged**
