### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash command is:

- `/format`: automatically format and lint the code

### CODE REVIEW

**Comment by seisman** [comment]
Could you please also fix another typo? Just need to add one more extra whitespace after `replaced`:
https://github.com/GenericMappingTools/pygmt/blob/d58720a49d0154ba6b46d7c7d89436d0a65a5f93/pygmt/datatypes/dataset.py#L164

**Comment by yvonnefroehlich** [comment]
> Could you please also fix another typo? Just need to add one more extra whitespace after `replaced`:
> 
> https://github.com/GenericMappingTools/pygmt/blob/d58720a49d0154ba6b46d7c7d89436d0a65a5f93/pygmt/datatypes/dataset.py#L164

Yep, sure. Done in commit https://github.com/GenericMappingTools/pygmt/pull/3211/commits/acf18eccccabc6d8e9eb3a55ba59fffd13abe2e8.

**Review by seisman — APPROVED** [review]

**Comment by seisman** [comment]
Let's keep this PR open for a while, just in case more typos are found before we release v0.12.0

**Comment by seisman** [comment]
Please also change `Github` to `GitHub`:
```
doc/changes.md
861:* Create Github Action workflow for reporting DVC image diffs ([#1104](https://github.com/GenericMappingTools/pygmt/pull/1104))

.github/workflows/ci_docs.yml
161:          # Need to have this file so that Github doesn't try to run Jekyll
```

**Review by michaelgrund — APPROVED** [review]

**Comment by yvonnefroehlich** [comment]
> Please also change `Github` to `GitHub`:
> 
> ```
> doc/changes.md
> 861:* Create Github Action workflow for reporting DVC image diffs ([#1104](https://github.com/GenericMappingTools/pygmt/pull/1104))
> 
> .github/workflows/ci_docs.yml
> 161:          # Need to have this file so that Github doesn't try to run Jekyll
> ```

Both fixed in commit https://github.com/GenericMappingTools/pygmt/pull/3211/commits/b1dbc97909d4c3fc62eb9df479b7c0a41f0709d7.

**Pull request merged**
