### PR TITLE
Consistent usage of whitespaces across gallery and tutorial examples

### LINKED ISSUE #2013: Inconsistent handling of whitespaces in titles and labels across gallery and tutorial examples
Up on [#1487](https://github.com/GenericMappingTools/pygmt/pull/1487) it is no longer required to use additional quotes for titles and labels containing whitespaces (`'+t"my title"'` or `'+l"my label"'`). In [#1950](https://github.com/GenericMappingTools/pygmt/pull/1950) the Intro to PyGMT [Making your first figure](https://www.pygmt.org/dev/get-started/first_figure.html#add-a-title) is already updated. However, several older gallery and tutorial examples still use this trick. To avoid confusion and for consistency, I think, we should adjust these examples.

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

Fixes #2013 

---------
**Overview of affected examples**
- [x] Cross-check in the end regarding completeness

_Tutorials_
- [x] [Frames, ticks, titles, and labels](https://www.pygmt.org/dev/tutorials/basics/frames.html#sphx-glr-tutorials-basics-frames-py) (including explanation in section [Title](https://www.pygmt.org/dev/tutorials/basics/frames.html#title))
- [x] [Plotting data points](https://www.pygmt.org/dev/tutorials/basics/plot.html#sphx-glr-tutorials-basics-plot-py)

_Gallery_
- [x] [Line fronts](https://www.pygmt.org/dev/gallery/lines/linefronts.html#sphx-glr-gallery-lines-linefronts-py)
- [x] [Line styles](https://www.pygmt.org/dev/gallery/lines/linestyles.html#sphx-glr-gallery-lines-linestyles-py)
- [x] [Roads](https://www.pygmt.org/dev/gallery/lines/roads.html#sphx-glr-gallery-lines-roads-py)
- [x] [Vector heads and tails](https://www.pygmt.org/dev/gallery/lines/vector_heads_tails.html#sphx-glr-gallery-lines-vector-heads-tails-py)
- [x] [Color points by categories](https://www.pygmt.org/dev/gallery/symbols/points_categorical.html#sphx-glr-gallery-symbols-points-categorical-py)
- [x] [Points with varying transparency](https://www.pygmt.org/dev/gallery/symbols/points_transparency.html#sphx-glr-gallery-symbols-points-transparency-py)
- [x] [Calculating grid gradient and radiance](https://www.pygmt.org/dev/gallery/images/grdgradient.html#sphx-glr-gallery-images-grdgradient-py)
- [x] [Clipping grid values](https://www.pygmt.org/dev/gallery/images/grdclip.html#sphx-glr-gallery-images-grdclip-py)
- [x] [3D Scatter plots](https://www.pygmt.org/dev/gallery/3d_plots/scatter3d.html#sphx-glr-gallery-3d-plots-scatter3d-py)
- [x] [Blockmean](https://www.pygmt.org/dev/gallery/histograms/blockm.html#sphx-glr-gallery-histograms-blockm-py)
- [x] [Histogram](https://www.pygmt.org/dev/gallery/histograms/histogram.html#sphx-glr-gallery-histograms-histogram-py)
- [x] [Colorbar](https://www.pygmt.org/dev/gallery/embellishments/colorbar.html#sphx-glr-gallery-embellishments-colorbar-py)

--------

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
In the section [Title](https://www.pygmt.org/dev/tutorials/basics/frames.html#title) of the Tutorial '_Frames, ticks, titles, and labels_':

```python
###############################################################################
# Title
# -----
#
# The figure title can be set by passing **+t**\ *title* to the ``frame``
# parameter of :meth:`pygmt.Figure.basemap`. Passing multiple arguments to
# ``frame`` can be done by using a list, as show in the example below.

fig = pygmt.Figure()
# region="IS" specifies Iceland using the ISO country code
fig.coast(shorelines="1/0.5p", region="IS", projection="M25c")
fig.basemap(frame=["a", "+tIceland"])
fig.show()

###############################################################################
# To use a title with multiple words, the title must be placed inside another
# set of quotation marks. To prevent the quotation marks from appearing in the
# figure title, the ``frame`` parameter can be passed in single quotation marks
# and the title can be passed in double quotation marks.

fig = pygmt.Figure()
# region="TT" specifies Trinidad and Tobago
fig.coast(shorelines="1/0.5p", region="TT", projection="M25c")
fig.basemap(frame=["a", '+t"Trinidad and Tobago"'])
fig.show()
```

- I would remove the part, which explains the double-quotation-mark trick.
- I would choose (and adjust) the code for the 'Trinidad and Tobago' map as an example for adding a title, and removed the code for the 'Island' map.

@seisman: Is this fine, or do you prefer to go with the 'Island' map as an example?

**Comment by seisman** [comment]
> * I would remove the part, which explains the double-quotation-mark trick.
> * I would choose (and adjust) the code for the 'Trinidad and Tobago' map as an example for adding a title, and removed the code for the 'Island' map.

Both sound good to me!

**Comment by seisman** [comment]
This PR looks good. Are there any more changes you want to make in this PR?

**Comment by seisman** [comment]
I think we also need to update a few tests.
```
tests/test_basemap.py:        frame=['x1p+l"Crustal age"', "y500+lDepth"],
tests/test_config.py:        region=[0, 10, 0, 10], projection="X5c/5c", frame=["af", '+t"Blue Annotation"']
tests/test_config.py:            frame=['xaf+l"red label"', "yaf", '+t"red annotation"'],
tests/test_config.py:        frame=["af", '+t"Blue Annotation"'],
```

These tests can be updated in this PR or in a separate PR.

**Comment by yvonnefroehlich** [comment]
> This PR looks good. Are there any more changes you want to make in this PR?

Regarding the gallery and tutorials, I think I have found and changed all affected examples. 

> I think we also need to update a few tests.

Good point! Yes.

> These tests can be updated in this PR or in a separate PR.

There is no real preference from my side on this. I can also open a new PR for updating the tests.

**Review by seisman — APPROVED** [review]
Good to merge.

**Review by michaelgrund — APPROVED** [review]

**Comment by weiji14** [comment]
> I think we also need to update a few tests.
> ```
> tests/test_basemap.py:        frame=['x1p+l"Crustal age"', "y500+lDepth"],
> tests/test_config.py:        region=[0, 10, 0, 10], projection="X5c/5c", frame=["af", '+t"Blue Annotation"']
> tests/test_config.py:            frame=['xaf+l"red label"', "yaf", '+t"red annotation"'],
> tests/test_config.py:        frame=["af", '+t"Blue Annotation"'],
> ```
> 
> These tests can be updated in this PR or in a separate PR.

Perhaps we should keep a few unit tests around that use the nested quotes, as a regression test to ensure backwards compatility is preserved?

**Comment by seisman** [comment]
> > I think we also need to update a few tests.
> > ```
> > tests/test_basemap.py:        frame=['x1p+l"Crustal age"', "y500+lDepth"],
> > tests/test_config.py:        region=[0, 10, 0, 10], projection="X5c/5c", frame=["af", '+t"Blue Annotation"']
> > tests/test_config.py:            frame=['xaf+l"red label"', "yaf", '+t"red annotation"'],
> > tests/test_config.py:        frame=["af", '+t"Blue Annotation"'],
> > ```
> >   
> > These tests can be updated in this PR or in a separate PR.
> 
> Perhaps we should keep a few unit tests around that use the nested quotes, as a regression test to ensure backwards compatibility is preserved?

We already have the following test in docstrings. Do you think it's enough?
https://github.com/GenericMappingTools/pygmt/blob/4902687d939f413f0249e11d6c722e3ac81eee94/pygmt/helpers/utils.py#L189-L198

**Comment by weiji14** [comment]
> > > I think we also need to update a few tests.
> > > ```
> > > tests/test_basemap.py:        frame=['x1p+l"Crustal age"', "y500+lDepth"],
> > > tests/test_config.py:        region=[0, 10, 0, 10], projection="X5c/5c", frame=["af", '+t"Blue Annotation"']
> > > tests/test_config.py:            frame=['xaf+l"red label"', "yaf", '+t"red annotation"'],
> > > tests/test_config.py:        frame=["af", '+t"Blue Annotation"'],
> > > ```
> > >   
> > > These tests can be updated in this PR or in a separate PR.
> > 
> > Perhaps we should keep a few unit tests around that use the nested quotes, as a regression test to ensure backwards compatibility is preserved?
> 
> We already have the following test in docstrings. Do you think it's enough?
> https://github.com/GenericMappingTools/pygmt/blob/4902687d939f413f0249e11d6c722e3ac81eee94/pygmt/helpers/utils.py#L189-L198

Oh yes true. That one should be enough.

**Pull request merged**
