### PR TITLE
Update baseline images for basemap

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Address #1217.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
All the new images make sense to me, except the `test_basemap_polar.png` one. I think it's a bug in GMT v6.2.0rc1, agree?

**Comment by meghanrjones** [comment]
Yes, I agree that it shows this bug: https://github.com/GenericMappingTools/gmt/issues/5120. I do not think it should be allowed to pass with the new image.

**Comment by seisman** [comment]
> Yes, I agree that it shows this bug: [GenericMappingTools/gmt#5120](https://github.com/GenericMappingTools/gmt/issues/5120). 

I don't think they're exactly the same bug. The equivalent GMT CLI is:
```
gmt basemap -R0/360/0/1000 -JP8c -Bafg -pdf map
```
It should NOT append any suffix (e.g., `E`) since it's a Cartesian polar projection.

image

> I do not think it should be allowed to pass with the new image.

Yes, I agree. I think I should keep the old `test_basemap_polar.png` image, and mark the test "xfail" for GMT 6.2.0rc1, right?

**Comment by meghanrjones** [comment]
> > Yes, I agree that it shows this bug: [GenericMappingTools/gmt#5120](https://github.com/GenericMappingTools/gmt/issues/5120).
> 
> I don't think they're exactly the same bug. The equivalent GMT CLI is:
> 
> ```
> gmt basemap -R0/360/0/1000 -JP8c -Bafg -pdf map
> ```
> 
> It should NOT append any suffix (e.g., `E`) since it's a Cartesian polar projection.
> 

I agree that no units should be appended. My understanding is that right now GMT assumes that all angles given to -JP are longitude, which is a problem for both #5120 and the PyGMT test. Up to you if you want to post this in the same issue or a new one.

> 
> > I do not think it should be allowed to pass with the new image.
> 
> Yes, I agree. I think I should keep the old `test_basemap_polar.png` image, and mark the test "xfail" for GMT 6.2.0rc1, right?

Yes to me.

**Comment by seisman** [comment]
> I agree that no units should be appended. My understanding is that right now GMT assumes that all angles given to -JP are longitude, which is a problem for both #5120 and the PyGMT test. Up to you if you want to post this in the same issue or a new one.

I think it's a new one. GMT v6.1.1 does not make this assumption. I'll post a new bug report.

**Review by meghanrjones — APPROVED** [review]

**Pull request merged**
