### PR TITLE
Replace "module" by "method" 

### PR DESCRIPTION
**Pull request by michaelgrund**
**Description of proposed changes**

This PR addresses #1828 and replaces the term "module" by "method" in several cases.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by meghanrjones — APPROVED** [review]

**Comment by seisman** [comment]
@michaelgrund Are you planning to replace all incorrect use of "module" in this one PR? If yes, there are still some other places that should be updated, for example, https://github.com/GenericMappingTools/pygmt/blob/main/examples/get-started/README.txt

**Comment by seisman** [comment]
Here are some places that I think should be updated.
- https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/grdview.py#L113
- https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/makecpt.py#L32
- https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/__init__.py#L2
- https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/grdproject.py#L38
- https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/grd2cpt.py#L36
- https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/grdimage.py#L136
- https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/examples/get-started/first_figure.py#L8

**Comment by michaelgrund** [comment]
> Here are some places that I think should be updated.
> 
>     * https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/grdview.py#L113
> 
>     * https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/makecpt.py#L32
> 
>     * https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/__init__.py#L2
> 
>     * https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/grdproject.py#L38
> 
>     * https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/grd2cpt.py#L36
> 
>     * https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/pygmt/src/grdimage.py#L136
> 
>     * https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/examples/get-started/first_figure.py#L8

Done! However, I'm not sure about the following:

- https://github.com/GenericMappingTools/pygmt/blob/f94b3999bb77deada760fabe03822d94084046a1/examples/get-started/first_figure.py#L40

**Review by seisman — APPROVED** [review]

**Pull request merged**
