### PR TITLE
Replace 'option' by 'parameter' in documentation of `pygmt.Figure.velo`, `pygmt.select`, `pygmt.which`

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

This PR aims to replace `option` by `parameter` in the API documentation of [pygmt.Figure.velo](https://www.pygmt.org/dev/api/generated/pygmt.Figure.velo.html#pygmt.Figure.velo), [pygmt.select](https://www.pygmt.org/dev/api/generated/pygmt.select.html#pygmt.select), and [pygmt.which](https://www.pygmt.org/dev/api/generated/pygmt.which.html#pygmt.which) as mention in https://github.com/GenericMappingTools/pygmt/pull/2082#issuecomment-1230847484.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by yvonnefroehlich** [comment]
Please see the desciption of the `z_subregion` parameter of the [`pygmt.select`](https://www.pygmt.org/latest/api/generated/pygmt.select.html#pygmt.select) function:

> z_subregion ([str](https://docs.python.org/3/library/stdtypes.html#str)) – min[/max][+a][+ccol][+i]. Pass all records whose 3rd column (z; col = 2) lies within the given range or is NaN (use skiprows to skip NaN records). If max is omitted then we test if z equals min instead. This means equality within 5 ULPs (unit of least precision; http://en.wikipedia.org/wiki/Unit_in_the_last_place). Input file must have at least three columns. To indicate no limit on min or max, specify a hyphen (-). If your 3rd column is absolute time then remember to supply coltypes="2T". To specify another column, append +ccol, and to specify several tests just repeat the z_subregion option as many times as you have columns to test. Note: When more than one z_subregion option is given then the reverse="z" option cannot be used. In the case of multiple tests you may use these modifiers as well: +a passes any record that passes at least one of your z tests [Default is all tests must pass], and +i reverses the tests to pass record with z value NOT in the given range. Finally, if +c is not used then it is automatically incremented for each new z_subregion option, starting with 2.

The lower part, starting with  `... to specify several tests just repeat the z_subregion option as many times as you have columns to test. Note: When more than one z_subregion option is given then the reverse="z" option cannot be used. ...` is identical to the [upstream GMT Documentation](https://docs.generic-mapping-tools.org/dev/gmtselect.html#z). I am unsure whether multiple  separate invocations of `z_subregion` work in PyGMT.

Please note, I did not replace `option` by `parameter` in this part yet.

**Review by michaelgrund — APPROVED** [review]

**Comment by seisman** [comment]
> The lower part, starting with `... to specify several tests just repeat the z_subregion option as many times as you have columns to test. Note: When more than one z_subregion option is given then the reverse="z" option cannot be used. ...` is identical to the [upstream GMT Documentation](https://docs.generic-mapping-tools.org/dev/gmtselect.html#z). I am unsure whether multiple separate invocations of `z_subregion` work in PyGMT.
> 
> Please note, I did not replace `option` by `parameter` in this part yet.

We need to use a list for this in PyGMT. For example, `-Z0/10 -Z20/30` should be `z_subregion=["0/10", "20/30"]` in PyGMT.

**Comment by yvonnefroehlich** [comment]
> > The lower part, starting with `... to specify several tests just repeat the z_subregion option as many times as you have columns to test. Note: When more than one z_subregion option is given then the reverse="z" option cannot be used. ...` is identical to the [upstream GMT Documentation](https://docs.generic-mapping-tools.org/dev/gmtselect.html#z). I am unsure whether multiple separate invocations of `z_subregion` work in PyGMT.
> > Please note, I did not replace `option` by `parameter` in this part yet.
> 
> We need to use a list for this in PyGMT. For example, `-Z0/10 -Z20/30` should be `z_subregion=["0/10", "20/30"]` in PyGMT.

Thanks @seisman! Should this be updated in this PR or better open a separate PR for updating the documentation of [pygmt.select](https://www.pygmt.org/dev/api/generated/pygmt.select.html#pygmt.select)?

**Review by seisman — APPROVED** [review]

**Comment by seisman** [comment]
> > > The lower part, starting with `... to specify several tests just repeat the z_subregion option as many times as you have columns to test. Note: When more than one z_subregion option is given then the reverse="z" option cannot be used. ...` is identical to the [upstream GMT Documentation](https://docs.generic-mapping-tools.org/dev/gmtselect.html#z). I am unsure whether multiple separate invocations of `z_subregion` work in PyGMT.
> > > Please note, I did not replace `option` by `parameter` in this part yet.
> > 
> > 
> > We need to use a list for this in PyGMT. For example, `-Z0/10 -Z20/30` should be `z_subregion=["0/10", "20/30"]` in PyGMT.
> 
> Thanks @seisman! Should this be updated in this PR or better open a separate PR for updating the documentation of [pygmt.select](https://www.pygmt.org/dev/api/generated/pygmt.select.html#pygmt.select)?

A separate PR should be good.

**Pull request merged**
