### PR TITLE
Fixes for using GMT 6.0.0rc1

### LINKED ISSUE #310: Not working with GMT 6.0.0rc1
Hi, I just installed `GMT 6.0.0rc1` on macOS through [homebrew](https://github.com/Homebrew/homebrew-core/pull/41119) and `pygmt` from source, but when try importing `pygmt`, I get the following error:

```
GMTVersionError: Using an incompatible GMT version 6.0.0rc1. Must be newer than 6.0.0.
```

### PR DESCRIPTION
**Pull request by claudiodsf**
Also fixes the error message on incompatible GMT version.

Fixes #310

### CODE REVIEW

**Comment by leouieda** [comment]
@claudiodsf thanks for trying it out and being on top of this!

**Comment by leouieda** [comment]
I'm rerunning the Mac tests to see if the failure was just a glitch.

**Comment by leouieda** [comment]
@claudiodsf that was an unrelated error with homebrew being outdated on Travis CI. I pushed a patch to your branch the build should pass now (fingers crossed).

**Comment by seisman** [comment]
@leouieda Since 6.0.0rc1 is already released, do you think we should switch to the conda-forge's gmt?

**Comment by leouieda** [comment]
@seisman yeah, I'm doing that now. I'm also updating all the setup here to use Azure and build on Windows.

**Comment by leouieda** [comment]
I removed the GMT compilation from the Travis builds. I think I'll back a cron job that is allowed to fail on Azure for GMT master later on so we make sure things keep working.

**Comment by leouieda** [comment]
@claudiodsf thank you for submitting the patch and noticing the problem so quickly! We really appreciate the contribution (keep them coming :). Please feel free to add yourself to the `AUTHORS.md` file.

**Comment by claudiodsf** [comment]
Thanks @leouieda! I'll add myself when I'll made a more significant contribution 😉

**Comment by weiji14** [comment]
Nice job @claudiodsf! Really appreciate the quick work, it's probably saved me an hour or two of time already today :smiley:

If you're looking to contribute more, you can take a look at those labelled [good-first-issues](https://github.com/GenericMappingTools/pygmt/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/GenericMappingTools/pygmt/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22). Or if there's some GMT function you need that's missing in PyGMT, open up an issue and we can start working on it.

**Pull request merged**
