### PR TITLE
Replace argument with parameter in coastlines tutorial

### PR DESCRIPTION
**Pull request by michaelgrund**
**Description of proposed changes**

Found further passages in the coastlines tutorial where "argument"  is incorrectly used. It's replaced by "parameter" in this PR.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by seisman — APPROVED** [review]

**Comment by core-man** [comment]
Great~ Only one minor additional revision

---

Change 10i to be 10c?
https://github.com/GenericMappingTools/pygmt/blob/d7de537dad6eaf1fb266da7ad3ac659483d915ce/examples/tutorials/coastlines.py#L86

**Comment by michaelgrund** [comment]
> 
> 
> Great~ Only one minor additional revision
> 
> Change 10i to be 10c?
> 
> https://github.com/GenericMappingTools/pygmt/blob/d7de537dad6eaf1fb266da7ad3ac659483d915ce/examples/tutorials/coastlines.py#L86

Of couse 😉. Will change it and let's have a look how it appears in sphinx.

**Comment by core-man** [comment]
Looks good on my phone.

**Comment by michaelgrund** [comment]
> 
> 
> Looks good on my phone.

Not here, some of the frame annotations are hidden. Not sure why. 

sphx_glr_coastlines_005

**Comment by seisman** [comment]
Let's change it to `15c`:

image

**Review by core-man — APPROVED** [review]

**Comment by core-man** [comment]
I can see the.frame annotations on my phone now.

**Pull request merged**
