### PR TITLE
Cache earth_relief_15s tile and set GMT_DATA_SERVER to use https

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

This PR caches the earth_relief_15s tile used in `examples/gallery/images/grdgradient.py`, but it may point to an upstream bug (https://github.com/GenericMappingTools/gmt/issues/5829). 

Also force GMT_DATA_SERVER to use https instead of HTTP, due to unknown GMT server issues.

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by weiji14** [comment]
Vercel build still failing... If you're trying to workaround the download error, maybe set the environment variable [`GMT_DATA_SERVER`](https://docs.generic-mapping-tools.org/6.2/gmt.conf.html#term-GMT_DATA_SERVER) to https://oceania.generic-mapping-tools.org as mentioned in https://github.com/GenericMappingTools/pygmt/pull/1548#issuecomment-931881372

**Comment by seisman** [comment]
> Vercel build still failing... If you're trying to workaround the download error, maybe set the environment variable [`GMT_DATA_SERVER`](https://docs.generic-mapping-tools.org/6.2/gmt.conf.html#term-GMT_DATA_SERVER) to [oceania.generic-mapping-tools.org](https://oceania.generic-mapping-tools.org) as mentioned in [#1548 (comment)](https://github.com/GenericMappingTools/pygmt/pull/1548#issuecomment-931881372), instead of deleting the gallery example.

I'm trying to find out why the GitHub Action CI fails. It's clear that something is wrong with downloading data files from the GMT server, but the GitHub Action CI should not download any files, because these files are available in CI caches.

**Comment by seisman** [comment]
https://github.com/GenericMappingTools/pygmt/runs/3763747598

The GitHub Action CI fails because the `grdgradient` example uses the 03s earth relief tile (already cached), but the 03s tile needs the 15s tile (not cached).

But why does the 03s tile needs the 15s tile? The map region is `-R-119.825/-119.4/37.6/37.825`, which is on the land. 

To reproduce the issue, I deleted my local cache and ran the following command, it's clear that both 03s and 15s tiles are downloaded.
```
$ gmt grdimage -R-119.825/-119.4/37.6/37.825 @earth_relief_03s -JQ10c -B -pdf map
grdblend [NOTICE]: Remote data courtesy of GMT data server china [http://china.generic-mapping-tools.org]

grdblend [NOTICE]: Earth Relief at 3x3 arc seconds tiles provided by SRTMGL3 (land only) [NASA/USGS].
grdblend [NOTICE]:   -> Download 1x1 degree grid tile (earth_relief_03s_g): N37W120
grdblend [NOTICE]: Earth Relief at 15x15 arc seconds provided by SRTM15+V2.1 [Tozer et al., 2019].
grdblend [NOTICE]:   -> Download 10x10 degree grid tile (earth_relief_15s_p): N30W120
```

**Comment by weiji14** [comment]
> The GitHub Action CI fails because the `grdgradient` example uses the 03s earth relief tile (already cached), but the 03s tile needs the 15s tile (not cached).
> 
> But why does the 03s tile needs the 15s tile? The map region is `-R-119.825/-119.4/37.6/37.825`, which is on the land. 

Seems like an upstream GMT bug? Can we isolate it solely to `grdcut`, or does the bug only appear for `grdgradient`/`grdimage`?

**Comment by seisman** [comment]
> > The GitHub Action CI fails because the `grdgradient` example uses the 03s earth relief tile (already cached), but the 03s tile needs the 15s tile (not cached).
> > But why does the 03s tile needs the 15s tile? The map region is `-R-119.825/-119.4/37.6/37.825`, which is on the land.
> 
> Seems like an upstream GMT bug? Can we isolate it solely to `grdcut`, or does the bug only appear for `grdgradient`/`grdimage`?

It also happens to `grdcut`. Reported to https://github.com/GenericMappingTools/gmt/issues/5829

**Review by weiji14 — APPROVED** [review]

**Pull request merged**
