### PR TITLE
Fix typos in documentation for Polar projection

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

This PR aims to fix a few typos in the documentation for the [Polar projection](https://www.pygmt.org/dev/projections/nongeo/polar.html).
In case 'r axis' (no hyphen) is preferred instead of 'r-axis', I can change this. Following PR https://github.com/GenericMappingTools/pygmt/pull/2028 'Earth' is  capitalized.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Review by maxrjones — APPROVED** [review]
Looks good, thanks!

If you wanted to improve this even further, it might be nice to have a comment describing the different sections rather than `# ============`, which does not render separate sections in https://www.pygmt.org/latest/projections/nongeo/polar.html#sphx-glr-projections-nongeo-polar-py.

**Review by seisman — APPROVED** [review]

**Review by michaelgrund — APPROVED** [review]

**Comment by yvonnefroehlich** [comment]
> If you wanted to improve this even further, it might be nice to have a comment describing the different sections rather than `# ============`, which does not render separate sections in https://www.pygmt.org/latest/projections/nongeo/polar.html#sphx-glr-projections-nongeo-polar-py.

Thanks @maxrjones! I can try to work on this in a separat PR.

Maybe we can further use the `+t` modifier of the `frame` parameter of  the `pygmt.Figure.basemap` method to set the titles? Currently, this is done via multiple calls of the `pygmt.Figure.text` method.

**Comment by maxrjones** [comment]
> Maybe we can further use the +t modifier of the frame parameter of the pygmt.Figure.basemap method to set the titles? Currently, this is done via multiple calls of the pygmt.Figure.text method.

Sorry for the very slow response. `+t` cannot plot on multiple lines, but it could be possible to use both `+t` and `+s` for a title and subtitle. The `+s` feature may not have been added when the example was originally made. However, It may be more confusing to use those modifiers rather than a couple text calls until the syntax for titles and subtitles is simplified.

**Comment by yvonnefroehlich** [comment]
> Sorry, just noticed https://github.com/GenericMappingTools/pygmt/pull/2110 as I'm slowly trying to catch up on GitHub notifications. I'll review that, thanks for opening the PR!

No worries and no hurry @maxrjones! The related PR is still WIP :wink:.

> +t cannot plot on multiple lines, but it could be possible to use both +t and +s for a title and subtitle. The +s feature may not have been added when the example was originally made. However, It may be more confusing to use those modifiers rather than a couple text calls until the syntax for titles and subtitles is simplified.

Up on PR https://github.com/GenericMappingTools/gmt/pull/4562 it is possible to accomplish line breaks within titles via `@^`. But of course, I am open to discuss this change during review.

**Pull request merged**
