### PR TITLE
Add test file for draft pull requests

### PR DESCRIPTION
**Pull request by willschlitzer**
As discussed in #584, this is a change of the .yaml files to create a test for draft pull requests. In a draft, the tests only run Python 3.9 on Ubuntu-latest. The entire test suite for different operating systems and Python versions only runs when the pull request is marked ready for review.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by willschlitzer** [comment]
@seisman @weiji14 I think I did this correctly and modified the appropriate .yaml files, but I'm not sure how to test it.

**Comment by seisman** [comment]
> In a draft, the tests only run Python 3.9 on Ubuntu-latest.

I can't say I like this.

**Comment by willschlitzer** [comment]
> > In a draft, the tests only run Python 3.9 on Ubuntu-latest.
> 
> I can't say I like this.

Would you recommend something differently, or not reducing the tests at all for drafts? My thought is that ubuntu typically runs the fastest, and this will provide a check on all the tests without requiring so many CI jobs for ever minor change, but still running the gamut of tests when the PR is marked ready for review.

**Comment by seisman** [comment]
@willschlitzer See #906 for the better implementation and don't forget to push the "Delete branch" button if you no longer need it.

**Pull request closed without merging**
