### PR TITLE
Rewrite the meca function to support offsetting and labeling beachballs

### LINKED ISSUE #1129: pygmt.Figure.meca offset not working
I am using pygmt to graph focal mechanisms with magnitude scale.
However, when I try to give it an offset so that they don't pile up the function doesn't seem to work.

I'm using :

```python
spec = dict (strike=strikes[0], dip=dips[0], rake=rakes[0], magnitude=magnitude [0])

fig.meca (spec, scale=f ".{0.002 * (2 ** magnitude[0])}c", longitude = lons [0], latitude = lats [0], depth = 25.0, convention = "aki", plot_longitude = lons [0], plot_latitude = lats[0] -10, offset=True) 
```
where all the objects are lists with real (float) values

**System information**
```
# Name                    Version                   Build  Channel
pygmt                     0.3.1              pyhd8ed1ab_0    conda-forge

```

Do I make something wrong?

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

In this PR, the core part of the `Figure.meca()` method is fully rewritten, because the original `Figure.meca()` implementation is too messy to read. The new implementation takes some inspiration from the original implementation and the changes in PR #1613, especially this comment about passing `pandas.DataFrame` directly https://github.com/GenericMappingTools/pygmt/pull/1613#discussion_r744349790.

**Main changes in the new implementation:**

- Use the universal `virtualfile_from_data` function to pass data (address #949)
- Pass `pandas.DataFrame` to the `virtualfile_from_data` directly, because `pandas.DataFrame` allows columns with different data types (proposed in https://github.com/GenericMappingTools/pygmt/pull/1613#discussion_r744349790 and works well)
- Support offsetting beachballs with the `plot_longitude` and `plot_latitude` columns/parameters (fixes #1129)
- Support labeling beachballs with the `event_name` column/parameter (address https://github.com/GenericMappingTools/pygmt/pull/516#issuecomment-657313059). [Here I use `event_name` rather than `label`, because `label` is usually aliased to GMT's `-l` option, and there is a plan to add `-l` to `meca` xref https://github.com/GenericMappingTools/gmt/issues/1973)
- Fix the inaccruate parameter names as reported in https://github.com/GenericMappingTools/pygmt/issues/1612

**BREAKING CHANGES**

1. Current fix for #1612 introduces a breaking change, but it's possible to make it backward-compatible. If backward-compatible is required, I can do it in a separate PR, to make this PR small.
2. When parameters like `longitude` are passed as the function parameter **and** are also given in dict/pd.DataFrame (e.g., `spec["longitude"]`), the behavior changes. In the old implementation, values in ``spec`` has high priority; but in the new implementation, values explicitly given as the function parameter override the values in ``spec``. I think the new implementation is more intuitive. The changes are backward-incompatible. 

**TODO in future PRs:**

There are some other `meca` related issues. I think it would be better to address them in separate PRs because the PR is already too large:

- [ ] #1466
- [ ] more checks (for example, checking `longitude` and `latitude` have the same length)
- [ ] More tests

### CODE REVIEW

**Comment by seisman** [comment]
Can someone give this PR a review?

**Comment by weiji14** [comment]
@jconvers, you mentioned during the EGU PyGMT meetup that you were up for testing code, would you like to try giving this Pull Request a review?

If you're keen, start by installing PyGMT from this branch using `pip install https://github.com/GenericMappingTools/pygmt/archive/refactor-meca.zip`. After that, try running the example code from https://www.pygmt.org/v0.6.1/gallery/seismology/meca.html and/or your make beachball plots. Let us know if you need help with anything!

**Comment by jconvers** [comment]
hi @weiji14 
I'm definitely up for it. I'll give it a shot.

**Comment by weiji14** [comment]
Oops sorry, wrong command! Try using `pip install git+https://github.com/GenericMappingTools/pygmt.git@refactor-meca`

**Comment by weiji14** [comment]
@sean0921, I see that you've made a nice GUI for plotting beachballs with `meca` at https://github.com/sean0921/simplemeca-flask. Do you have time to take a look and review this Pull Request to make sure things work as expected? E.g. using `pip install git+https://github.com/GenericMappingTools/pygmt.git@refactor-meca` to install PyGMT from this branch. Or if you have any suggestions on what could be improved, that would be useful for us to know as well!

**Review by sean0921 — COMMENTED** [review]
I've roughly check this change with running my project depending on it.  It doesn't break my project. 
https://imgur.com/a/dVOL20H

If there's no more detail found that could be corrected by me, I will approve this change in today (before 2021/7/2 16:00 UTC)

**Review by sean0921 — APPROVED** [review]

**Pull request merged**
