### PR TITLE
Add contour map tutorial script

### PR DESCRIPTION
**Pull request by willschlitzer**
I created a tutorial on the usage of the grdcontour method to demonstrate creating a plot with contour lines and adjusting the intervals, annotations, and limits.

### CODE REVIEW

**Comment by seisman** [comment]
@willschlitzer Thanks for contributing the example.

I have two major comments before reviewing the details:

1. You're working on your master branch. That's not a good practice. Imagine that when we merge more commits into our master branch, your master branch will be in conflict with our master branch. It will cause a lot of troubles for you. You should create a branch and work on that branch instead.
2. No need to include ipynb files in the repository.

**Comment by willschlitzer** [comment]
@seisman Thanks for the reply. Other than a few typo corrections in docstrings/comments, this is my first attempt at open source contributing. I'll create a separate branch for future contributions; sorry about the .ipynb file.

**Comment by seisman** [comment]
I just see that you have created a new branch (https://github.com/willschlitzer/pygmt/tree/3d_map_example) and are working on it.

I'm closing this PR and looking forward to your new PR from your new branch.

**Comment by willschlitzer** [comment]
@seisman Thanks for the feedback; resubmitted the PR under a new branch

**Pull request closed without merging**
