### PR TITLE
Rename tutorials using underscores

### LINKED ISSUE #1039: Rename files in the tutorials using underscores
Following #1034, we should use underscores for all Python files. We did the renaming in recent PRs, but there are still a few files in the [`examples/tutorials`](https://github.com/GenericMappingTools/pygmt/tree/master/examples/tutorials) directory that should be changed.

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

This PR renames tutorials with underscores, rather than dashes.

Fixes #1039

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
```
/home/runner/work/pygmt/pygmt/doc/index.rst:16: WARNING: toctree contains reference to nonexisting document 'tutorials/first-figure'
looking for now-outdated files... none found
/home/runner/work/pygmt/pygmt/doc/index.rst:26: WARNING: toctree contains reference to nonexisting document 'tutorials/contour-map'
/home/runner/work/pygmt/pygmt/doc/index.rst:26: WARNING: toctree contains reference to nonexisting document 'tutorials/earth-relief'
/home/runner/work/pygmt/pygmt/doc/index.rst:26: WARNING: toctree contains reference to nonexisting document 'tutorials/3d-perspective-image'
```

Need to update the file `doc/index.rst`.

**Comment by meghanrjones** [comment]
> ```
> /home/runner/work/pygmt/pygmt/doc/index.rst:16: WARNING: toctree contains reference to nonexisting document 'tutorials/first-figure'
> looking for now-outdated files... none found
> /home/runner/work/pygmt/pygmt/doc/index.rst:26: WARNING: toctree contains reference to nonexisting document 'tutorials/contour-map'
> /home/runner/work/pygmt/pygmt/doc/index.rst:26: WARNING: toctree contains reference to nonexisting document 'tutorials/earth-relief'
> /home/runner/work/pygmt/pygmt/doc/index.rst:26: WARNING: toctree contains reference to nonexisting document 'tutorials/3d-perspective-image'
> ```
> 
> Need to update the file `doc/index.rst`.

Thanks, fixed in ef0d43e33eda43ab5f1d09fd9e4d8094035997b0

**Comment by michaelgrund** [comment]
> 
> 
> > There may be something wrong with GitHub.
> > I clicked the "Squash and merge" button a few minutes ago and it froze.
> > Now it seems the changes in this PR are already in the master branch, but this PR is still unmerged. Is this what you're seeing?
> 
> Yes, I see the same thing. The [commit log](https://github.com/GenericMappingTools/pygmt/commits/master) shows this as merged, but the PR does not reflect that.

I see the same.

**Comment by seisman** [comment]
Maybe GitHub did the "git merge" command, froze and then forgot to close the PR.

Let's keep this PR open for a while and see if anything changes.

**Comment by weiji14** [comment]
https://www.githubstatus.com/. Parts of GitHub are currently down. Need to wait it out and be careful for a while.

**Comment by seisman** [comment]
GitHub is up now. Nothing changes. I'll close the PR.

**Pull request closed without merging**
