### PR TITLE
Tutorial "Plotting data points": Change pen color for better contrast

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

This PR suggests to change the `pen` color to improve the contrast in the tutorial "Plotting data points":

| `pen="black"` | `pen="white"`
| --- | --- |
| black_outline | white_outline |
**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
> change the `pen` color to improve the contrast in the tutorial "Plotting data points":

But the other two images in the same gallery example all use a "black" pen.

**Comment by yvonnefroehlich** [comment]
> > change the `pen` color to improve the contrast in the tutorial "Plotting data points":
> 
> But the other two images in the same gallery example all use a "black" pen.

Yes, but there the circles are not filled with a dark color, but with white color. So, the black outline of the circles is clearly visible.

**Comment by michaelgrund** [comment]
Not sure if the white outline is a better solution across the whole plot since for the bright colors (right upper corner) the black outline works much better.

**Comment by seisman** [comment]
> > > change the `pen` color to improve the contrast in the tutorial "Plotting data points":
> > 
> > 
> > But the other two images in the same gallery example all use a "black" pen.
> 
> Yes, but there the circles are not filled with a dark color, but with white color. So, the black outline of the circles is clearly visible.

The 3rd image is an improved version of the 2nd image (by setting `fill=data.depth_km` and `cmap=True`), so it would be better to keep the code changes as minimal as possible. Otherwise, we need to at least add one sentence explaining why we change the pen color to `white`.

**Comment by seisman** [comment]
> Not sure if the white outline is a better solution across the whole plot since for the bright colors (right upper corner) the black outline works much better.

Agree with this point.

**Comment by yvonnefroehlich** [comment]
I am sorry for the delay in my answer here 🙁. 

> > Not sure if the white outline is a better solution across the whole plot since for the bright colors (right upper corner) the black outline works much better.
> 
> Agree with this point.

Yes, for these three data points, a black outline works better. But the majority of data points has a dark fill color, for which a white outline color works better.

>>>> change the pen color to improve the contrast in the tutorial "Plotting data points":

>>> But the other two images in the same gallery example all use a "black" pen.

>> Yes, but there the circles are not filled with a dark color, but with white color. So, the black outline of the circles is clearly visible.

> The 3rd image is an improved version of the 2nd image (by setting `fill=data.depth_km` and `cmap=True`), so it would be better to keep the code changes as minimal as possible. Otherwise, we need to at least add one sentence explaining why we change the pen color to `white`.

I am fine with adding a comment explaining the change from a black to a white outline (`pen`) color.
But as this PR brought up more discussion than I expected, it is maybe easier to leave the tutorial as is, as the outline color is only a detail.

**Comment by seisman** [comment]
I'm inclined to close this PR.

**Pull request closed without merging**
