### PR TITLE
Run pytest with `--color=yes` to force GitHub Actions logs to have color

### PR DESCRIPTION
**Pull request by weiji14**
**Description of proposed changes**

GitHub Actions does not show colour outputs for pytest by default (https://github.com/pytest-dev/pytest/issues/7443), but it can be enabled using `--color=yes` flag.

| Before (black & white :panda_face:) | After (color :rainbow:) |
|--|--|
| image | image |

Enables color output for pytest on:
- ci_doctests.yaml
- ci_tests.yaml
- ci_tests_dev.yaml
- ci_tests_legacy.yaml

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash command is:

- `/format`: automatically format and lint the code

### CODE REVIEW

**Comment by seisman** [comment]
Can we add it directly to https://github.com/GenericMappingTools/pygmt/blob/97a6f30cf3a262d3f6028a40b7c61836af86c25f/pyproject.toml#L169?

**Comment by weiji14** [comment]
> Can we add it directly to
> 
> https://github.com/GenericMappingTools/pygmt/blob/97a6f30cf3a262d3f6028a40b7c61836af86c25f/pyproject.toml#L169
> ?

We could do that yes. I'm just not sure how everyone's terminals works with color output.

**Comment by seisman** [comment]
> I'm just not sure how everyone's terminals works with color output.

```
--color=color         Color terminal output (yes/no/auto)
```
Maybe `--color=auto` and assume that pytest works?

**Comment by weiji14** [comment]
> > I'm just not sure how everyone's terminals works with color output.
> 
> ```
> --color=color         Color terminal output (yes/no/auto)
> ```
> 
> Maybe `--color=auto` and assume that pytest works?

Should be auto by default already I think. It's just that `--color=auto` doesn't work on GitHub Actions (see thread at https://github.com/pytest-dev/pytest/issues/7443).

**Comment by weiji14** [comment]
Ok, switched to putting `--color=yes` in pytest addopts. Activating the benchmark workflow just to make sure the color output works (otherwise the CI tests won't run with a change to pyproject.toml only).

**Comment by weiji14** [comment]
So much performance improvement from adding colour :rofl:

Pytest log output looks colored at https://github.com/GenericMappingTools/pygmt/actions/runs/9950591916/job/27488697947?pr=3330#step:7:106

image

**Review by seisman — APPROVED** [review]

**Pull request merged**
