### PR TITLE
Debug Windows + Python 3.6

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Related to #693.

Fixes #

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

**Notes**

- You can write `/format` in the first line of a comment to lint the code automatically

### CODE REVIEW

**Comment by seisman** [comment]
The GMT library `gmt.dll` exists, but GMT still can't find/load it. Perhaps a broken library?

I'm wondering if it's really worth the debugging time, as we will drop Python 3.6 in the next few months.

**Comment by weiji14** [comment]
> The GMT library `gmt.dll` exists, but GMT still can't find/load it. Perhaps a broken library?
> 
> I'm wondering if it's really worth the debugging time, as we will drop Python 3.6 in the next few months.

What I'm worried about is whether the PyGMT v0.2.1 release works for Python 3.6 users on Windows. I say we leave this PR hanging for now and see **if** someone reports it (in which case we can tell them to upgrade to Python 3.7 or decide to work on this PR and release PyGMT v0.2.2 as a quickfix).

**Comment by seisman** [comment]
> we can tell them to upgrade to Python 3.7

This is what we should do to save us more time.

> we could also disable the Windows Python 3.6 master CI tests to stop the annoying notifications.

Yes, please do it.

**Comment by seisman** [comment]
We dropped Python 3.6 support in #699. This PR is no longer needed.

**Pull request closed without merging**
