### PR TITLE
load_earth_relief now can load gebco, gebcosi and synbath datasets with GMT 6.3

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

As mentioned in https://github.com/GenericMappingTools/pygmt/issues/2225#issuecomment-1340896454, after PR #2266 is merged, gebco, gebcosi and synbath dataset should work with GMT 6.3. This PR remove the exception when gebco/gebcosi/synbath datasets are used with GMT 6.3.

Fixes https://github.com/GenericMappingTools/pygmt/issues/2225.

Notes that:

Some tests fail with GMT 6.3 in the GMT Legacy Tests workflow (https://github.com/GenericMappingTools/pygmt/actions/runs/3784213311). These tests should pass after the changes in this PR.

Let's see the workflow results trigged by this PR https://github.com/GenericMappingTools/pygmt/actions/runs/3795048765.

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
> Let's see the workflow results trigged by this PR [GenericMappingTools/pygmt/actions/runs/3795048765](https://github.com/GenericMappingTools/pygmt/actions/runs/3795048765).

It seems there are some failures in the GMT Legacy Tests, some are caused by the missing IPython package and some are doctests. 

But at least the tests with gebco/gebcosi/synbath now pass.

**Comment by seisman** [comment]
> > Let's see the workflow results trigged by this PR [GenericMappingTools/pygmt/actions/runs/3795048765](https://github.com/GenericMappingTools/pygmt/actions/runs/3795048765).
> 
> It seems there are some failures in the GMT Legacy Tests, some are caused by the missing IPython package and some are doctests.
> 
> But at least the tests with gebco/gebcosi/synbath now pass.

Some TODOs:

1. Update the release checklist to check the "GMT Legacy Tests" to make sure the new release still work with old GMT versions
2. Update the release checklist to check the "GMT Dev Tests" to make sure the new release will work with GMT dev version.
3. IPython is not installed in the "GMT Legacy Tests"
4. It's likely that the "Tests" workflow doesn't run the full tests (including all doctests) on  Wednesday https://github.com/GenericMappingTools/pygmt/blob/16fc565c25dc013f31438dadc704e3febddeb158/.github/workflows/ci_tests.yaml#L139

**Comment by weiji14** [comment]
> 1. Update the release checklist to check the "GMT Legacy Tests" to make sure the new release still work with old GMT versions
> 2. Update the release checklist to check the "GMT Dev Tests" to make sure the new release will work with GMT dev version.

Maybe do this after the PyGMT v0.8.0 release? We'll just manually verify this for now, so that the release isn't delayed any longer.

> 3. IPython is not installed in the "GMT Legacy Tests"
> 4. It's likely that the "Tests" workflow doesn't run the full tests (including all doctests) on  Wednesday

Opened PR at https://github.com/GenericMappingTools/pygmt/pull/2283 to add `ipython`. Should the "GMT Legacy Tests" run the full tests (i.e. `make fulltest`) or just the regular tests without docstrings (i.e. `make test`).?

**Review by weiji14 — APPROVED** [review]
Changes should be ok. Maybe it's easier to merge this PR first, and then we can run the GMT Legacy Tests properly in #2283.

**Pull request merged**
