### PR TITLE
NEP29: Test PyGMT on NumPy 1.26

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

Bumps [numpy](https://github.com/numpy/numpy) from 1.25 to 1.26. [NumPy 1.26.0](https://github.com/numpy/numpy/releases/tag/v1.26.0) was released on 18 Jun 2023.
- [Release notes](https://github.com/numpy/numpy/releases)
- [Changelog](https://numpy.org/doc/1.26/release/1.26.0-notes.html)
- [Commits](https://github.com/numpy/numpy/compare/v1.25.0...v1.26.0)

This is in line with PyGMT's policy on [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) at https://www.pygmt.org/v0.9.0/maintenance.html#dependencies-policy, xref #1074.

Note that the branch protection rules at [GenericMappingTools/pygmt/settings/branches](https://github.com/GenericMappingTools/pygmt/settings/branches) will need to be changed to use Python 3.11/Numpy 1.26 instead of Python 3.11/Numpy 1.25 before this Pull Request is merged.

Supersedes #2581

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
Need to wait for https://github.com/conda-forge/numpy-feedstock/pull/297

**Comment by seisman** [comment]
After bumping NumPy 1.25 to 1.26, we have 170 failures. These failures are all caused by the Ghostscript versions. 

For unknown reasons (complicated package dependency), with NumPy 1.25, gs 9.54 is installed but with NumPy 1.26, gs 10.02.0 is installed.

**Comment by seisman** [comment]
> After bumping NumPy 1.25 to 1.26, we have 170 failures. These failures are all caused by the Ghostscript versions.
> 
> For unknown reasons (complicated package dependency), with NumPy 1.25, gs 9.54 is installed but with NumPy 1.26, gs 10.02.0 is installed.

We have a few options to address these failures:

- Pin gs to 9.54 in the Dev Tests
- Pin gs to 10.02.0 in the regular Tests and update all baseline images

**Comment by weiji14** [comment]
> * Pin gs to 9.54 in the Dev Tests
> 
> * Pin gs to 10.02.0 in the regular Tests and update all baseline images

We'll need to update the baseline images for gs 10.02.0 eventually, so I'd prefer option 2. But I'm worried if we can't install gs 10.02 on Python 3.9 / NumPy 1.22, causing the tests to fail when we update the base images :sweat_smile:

**Comment by seisman** [comment]
> But I'm worried if we can't install gs 10.02 on Python 3.9 / NumPy 1.22, causing the tests to fail when we update the base images

Pin gs to 10.02.0 seems working https://github.com/GenericMappingTools/pygmt/pull/2694 for the Tests CI.

**Review by weiji14 — APPROVED** [review]
Pinning to gs 9.54 in #2754 allows the tests to pass on NumPy 1.26 (previously tests were failing due to image differences with gs 10.02).

@seisman, feel free to merge after the tests pass. Remember to update the branch protection rules too!

**Pull request merged**
