### PR TITLE
Fix the wrong example in contributing guide

### PR DESCRIPTION
**Pull request by seisman**
**Description of proposed changes**

- `psbasemap` should be `basemap`
- `portrait` is not a valid argument

**Reminders**

- [X] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to docstrings or tutorials.

### CODE REVIEW

**Comment by weiji14** [comment]
Hmm, it still says I'm not authorized to merge.
image

**Comment by seisman** [comment]
pygmt was designed long time ago, and the GMT modern mode also changes since then, so there may be some legacy codes left.

**Comment by seisman** [comment]
@weiji14 What does it say when you click the "You're not authorized" link?

**Comment by weiji14** [comment]
It directs me to this link https://help.github.com/en/articles/about-protected-branches.

**Comment by seisman** [comment]
@weiji14 I just changed the permission level of the [python team](https://github.com/orgs/GenericMappingTools/teams/python) to "maintain". Hopefully it grants you the merge permission.

**Comment by weiji14** [comment]
Cool, I see that I can do 'squash and merge' now! Thanks!

**Pull request merged**
