### PR TITLE
Use consistently 1-D, 2-D, or 3-D (with hyphen and capitalized)

### PR DESCRIPTION
**Pull request by yvonnefroehlich**
**Description of proposed changes**

Corresponding to this upstream GMT PR https://github.com/GenericMappingTools/gmt/pull/7157, this PR aims to use consistently `x-D` (with hypen and capitalized, i.e., not `xd` or `xD`) for x=1,2,3.
- [x] src (documentation)
- [x] examples/gallery
- [x] examples/tutorials
- [x] datasets
- [x] helpers
- [x] tests

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If wrapping a new module, open a 'Wrap new GMT module' issue and submit reasonably-sized PRs.
- [ ] If adding new functionality, add an example to docstrings or tutorials.
- [ ] Use underscores (not hyphens) in names of Python files and directories.

**Slash Commands**

You can write slash commands (`/command`) in the first line of a comment to perform
specific operations. Supported slash commands are:

- `/format`: automatically format and lint the code
- `/test-gmt-dev`: run full tests on the latest GMT development version

### CODE REVIEW

**Comment by seisman** [comment]
I'm not sure about these changes. It seems numpy prefers to use xD instead (e.g., see https://numpy.org/doc/stable/user/basics.creation.html#id1).

**Comment by seisman** [comment]
Ping @GenericMappingTools/pygmt-maintainers to decide if we should use 2-D (consistent with GMT) or 2D (consistent with NumPy).

**Comment by michaelgrund** [comment]
> Ping @GenericMappingTools/pygmt-maintainers to decide if we should use 2-D (consistent with GMT) or 2D (consistent with NumPy).

I have no strong opinion on that, would be happy with both solutions as long as we have a consistent naming.

**Review by seisman — APPROVED** [review]
OK with the changes.

**Pull request merged**
